/**************************************************/
IF OBJECT_ID(N'CALIDAD.DQ_DOMINIO', N'U') IS NOT NULL
BEGIN
	--ALTER TABLE CALIDAD.DQ_DOMINIO DROP CONSTRAINT IF EXISTS FK_CAT_SENSIBILIDAD_DOMINIO;
	--ALTER TABLE CALIDAD.DQ_DOMINIO DROP CONSTRAINT IF EXISTS FK_CAT_ESTCONCEPTUALIZACION_DOMINIO;
	SELECT 1;
END;


IF OBJECT_ID(N'CALIDAD.DQ_ATRIBUTO', N'U') IS NOT NULL
BEGIN
	ALTER TABLE CALIDAD.DQ_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_DOMINIO_ATRIBUTO;
	--ALTER TABLE CALIDAD.DQ_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_CAT_SENSIBILIDAD_ATRIBUTO;
	--ALTER TABLE CALIDAD.DQ_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_CAT_ESTCONCEPTUALIZACION_ATRIBUTO;
END;


IF OBJECT_ID(N'CALIDAD.DQ_REGLA_ATRIBUTO', N'U') IS NOT NULL
BEGIN
	ALTER TABLE CALIDAD.DQ_REGLA_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_DOMINIO_REGLAATRIBUTO;
	ALTER TABLE CALIDAD.DQ_REGLA_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_ATRIBUTO_REGLAATRIBUTO;
	ALTER TABLE CALIDAD.DQ_REGLA_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_CAT_DIMCALIDAD_REGLAATRIBUTO;
	ALTER TABLE CALIDAD.DQ_REGLA_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_CAT_ESTCONCEPTUALIZACION_REGLAATRIBUTO;
END;


IF OBJECT_ID(N'CALIDAD.DQ_REGLA_ATRIBUTO', N'U') IS NOT NULL
BEGIN
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA DROP CONSTRAINT IF EXISTS FK_EJECUCION_RESREGLA;
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA DROP CONSTRAINT IF EXISTS FK_DOMINIO_RESREGLA;
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA DROP CONSTRAINT IF EXISTS FK_ATRIBUTO_RESREGLA;
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA DROP CONSTRAINT IF EXISTS FK_CAT_DIMCALIDAD_RESREGLA;
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA DROP CONSTRAINT IF EXISTS FK_CAT_REGLAATRIBUTO_RESREGLA;
END;


IF OBJECT_ID(N'CALIDAD.DQ_RESULTADO_REGLA_DETALLE', N'U') IS NOT NULL
BEGIN
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE DROP CONSTRAINT IF EXISTS FK_EJECUCION_RESREGLADET;
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE DROP CONSTRAINT IF EXISTS FK_DOMINIO_RESREGLADET;
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE DROP CONSTRAINT IF EXISTS FK_ATRIBUTO_RESREGLADET;
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE DROP CONSTRAINT IF EXISTS FK_CAT_DIMCALIDAD_RESREGLADET;
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE DROP CONSTRAINT IF EXISTS FK_CAT_REGLAATRIBUTO_RESREGLADET;
END;


IF OBJECT_ID(N'CALIDAD.DQ_RESULTADO_DOMINIO', N'U') IS NOT NULL
BEGIN
	ALTER TABLE CALIDAD.DQ_RESULTADO_DOMINIO DROP CONSTRAINT IF EXISTS FK_EJECUCION_RESDOMINIO;
	ALTER TABLE CALIDAD.DQ_RESULTADO_DOMINIO DROP CONSTRAINT IF EXISTS FK_DOMINIO_RESDOMINIO;
	ALTER TABLE CALIDAD.DQ_RESULTADO_DOMINIO DROP CONSTRAINT IF EXISTS FK_CAT_DIMCALIDAD_RESDOMINIO;
END;


IF OBJECT_ID(N'CALIDAD.DQ_RESULTADO_ATRIBUTO', N'U') IS NOT NULL
BEGIN
	ALTER TABLE CALIDAD.DQ_RESULTADO_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_EJECUCION_RESATRIBUTO;
	ALTER TABLE CALIDAD.DQ_RESULTADO_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_DOMINIO_RESATRIBUTO;
	ALTER TABLE CALIDAD.DQ_RESULTADO_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_ATRIBUTO_RESATRIBUTO;
	ALTER TABLE CALIDAD.DQ_RESULTADO_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_CAT_DIMCALIDAD_RESATRIBUTO;
END;


IF OBJECT_ID(N'CALIDAD.DQ_RESULTADO_REGISTRO', N'U') IS NOT NULL
BEGIN
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGISTRO DROP CONSTRAINT IF EXISTS FK_EJECUCION_RESREGISTRO;
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGISTRO DROP CONSTRAINT IF EXISTS FK_DOMINIO_RESREGISTRO;
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGISTRO DROP CONSTRAINT IF EXISTS FK_CAT_DIMCALIDAD_RESREGISTRO;
END;


IF OBJECT_ID(N'CALIDAD.DQ_EJECUCION_DOMINIO', N'U') IS NOT NULL
BEGIN
	ALTER TABLE CALIDAD.DQ_EJECUCION_DOMINIO DROP CONSTRAINT IF EXISTS FK_EJECUCION_EJECDOMINIO;
	ALTER TABLE CALIDAD.DQ_EJECUCION_DOMINIO DROP CONSTRAINT IF EXISTS FK_DOMINIO_EJECDOMINIO;
END;
/**************************************************/


/**************************************************/
IF OBJECT_ID(N'CALIDAD.DQ_DOMINIO', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.DQ_DOMINIO;
END;
CREATE TABLE CALIDAD.DQ_DOMINIO (
	DOMINIO_ID	INTEGER IDENTITY(1,1) PRIMARY KEY
	,NOMBRE VARCHAR(50)
	,TIPO_DOMINIO_ID INT
	,DESCRIPCION VARCHAR(500)
	,CONCEPTO_CLAVE_NEGOCIO VARCHAR(100)
	,PROCESO_CLAVE_ASOCIADO VARCHAR(100)
	--,SENSIBILIDAD_ID INT
	,SENSIBILIDAD VARCHAR(20)
	,KDE_NUM INT
	,MCA_REGLAS_CALIDAD BIT
	--,ESTADO_CONCEPTUALIZACION_ID INT
	,ESTADO_CONCEPTUALIZACION VARCHAR(20)
	,PRIORIDAD INT
	,OLA_IMPLEMENTACION INT
	,VIGENCIA_INICIO DATE
	,VIGENCIA_FIN DATE
	,VERSION VARCHAR(20)
	,FECHA_REGISTRO DATETIME
	,FECHA_ACTUALIZACION DATETIME
	,USUARIO_REGISTRO VARCHAR(25)
	,USUARIO_ACTUALIZACION VARCHAR(25)
);


IF OBJECT_ID(N'CALIDAD.DQ_ATRIBUTO', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.DQ_ATRIBUTO;
END;
CREATE TABLE CALIDAD.DQ_ATRIBUTO (
	ATRIBUTO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	,DOMINIO_ID INT
	,NOMBRE_TECNICO VARCHAR(100)
	,DESCRIPCION_FUNCIONAL VARCHAR(500)
	,CONCEPTO_NEGOCIO VARCHAR(100)
	,TIPO_DATO VARCHAR(20)
	,FORMATO VARCHAR(200)
	,LONGITUD INT
	,PRECISION INT
	,ESCALA INT
	,UNIDAD_MEDIDA VARCHAR(25)
	,VALOR_DEFECTO VARCHAR(25)
	,MCA_OBLIGATORIO BIT
	,MCA_IDENTIFICADOR BIT
	,MCA_LLAVE_NEGOCIO BIT
	,MCA_KDE BIT
	,PESO_ATRIBUTO FLOAT
	,CATALOGO_VALORES VARCHAR(500)
	--,SENSIBILIDAD_ID INT
	,SENSIBILIDAD VARCHAR(20)
	--,ESTADO_CONCEPTUALIZACION_ID INT
	,ESTADO_CONCEPTUALIZACION VARCHAR(20)
	,VIGENCIA_INICIO DATE
	,VIGENCIA_FIN DATE
	,VERSION VARCHAR(20)
	,FECHA_ULTIMO_CONTROL DATETIME
	,OBSERVACIONES VARCHAR(500)
	,FECHA_REGISTRO DATETIME
	,FECHA_ACTUALIZACION DATETIME
	,USUARIO_REGISTRO VARCHAR(25)
	,USUARIO_ACTUALIZACION VARCHAR(25)
);


IF OBJECT_ID(N'CALIDAD.DQ_REGLA_ATRIBUTO', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.DQ_REGLA_ATRIBUTO;
END;
CREATE TABLE CALIDAD.DQ_REGLA_ATRIBUTO (
	REGLA_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	,DOMINIO_ID INT
	,ATRIBUTO_ID INT
	,DIMENSION_CALIDAD_ID INT
	,DESCRIPCION_REGLA VARCHAR(500)
	,EXPRESION_REGULAR VARCHAR(500)
	,UMBRAL_MINIMO FLOAT
	,MARGEN_TOLERANCIA FLOAT
	,ES_CRITICA_GATING BIT
	,PESO_REGLA FLOAT
	,RESPONSABLE VARCHAR(100)
	,ESTADO VARCHAR(15)
	,VIGENCIA_INICIO DATE
	,VIGENCIA_FIN DATE
	,VERSION VARCHAR(20)
	,OBSERVACIONES VARCHAR(500)
	,FECHA_REGISTRO DATETIME
	,FECHA_ACTUALIZACION DATETIME
	,USUARIO_REGISTRO VARCHAR(25)
	,USUARIO_ACTUALIZACION VARCHAR(25)
);


IF OBJECT_ID(N'CALIDAD.CAT_DIMENSION_CALIDAD', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.CAT_DIMENSION_CALIDAD;
END;
CREATE TABLE CALIDAD.CAT_DIMENSION_CALIDAD (
	DIMENSION_CALIDAD_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	,NOMBRE VARCHAR(100)
	,DEFINICION VARCHAR(500)
	,ESTADO VARCHAR(15)
);


IF OBJECT_ID(N'CALIDAD.DQ_RESULTADO_REGLA_DETALLE', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE;
END;
CREATE TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE (
	DETALLE_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	,EJECUCION_ID INT
	,DOMINIO_ID INT
	,ATRIBUTO_ID INT
	,REGLA_ID INT
	,DIMENSION_CALIDAD_ID INT
	,ID_REGISTRO_FUENTE VARCHAR(100)
	,VALOR_OBSERVADO VARCHAR(4000)
	,ESTADO_VALIDACION VARCHAR(15)
	,CODIGO_ERROR VARCHAR(4000)
	,DESCRIPCION_ERROR VARCHAR(500)
	,FECHA_EVENTO DATETIME
);


IF OBJECT_ID(N'CALIDAD.DQ_RESULTADO_REGLA', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.DQ_RESULTADO_REGLA;
END;
CREATE TABLE CALIDAD.DQ_RESULTADO_REGLA (
	RESULTADO_REGLA_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	,EJECUCION_ID INT
	,DOMINIO_ID INT
	,ATRIBUTO_ID INT
	,REGLA_ID INT
	,DIMENSION_CALIDAD_ID INT
	,REGISTROS_EVALUADOS BIGINT
	,REGISTROS_CUMPLE BIGINT
	,REGISTROS_CUMPLE_PARCIAL BIGINT
	,REGISTROS_NO_CUMPLE BIGINT
	,TASA_CUMPLIMIENTO FLOAT
	,TASA_ERROR FLOAT
	,UMBRAL_MINIMO FLOAT
	,MARGEN_TOLERANCIA FLOAT
	,MCA_UMBRAL_CUMPLIDO BIT
	,PESO_REGLA FLOAT
	,SCORE_REGLA FLOAT
	,FECHA_CALCULO DATETIME
);


IF OBJECT_ID(N'CALIDAD.DQ_RESULTADO_ATRIBUTO', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.DQ_RESULTADO_ATRIBUTO;
END;
CREATE TABLE CALIDAD.DQ_RESULTADO_ATRIBUTO (
	RESULTADO_ATRIBUTO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	,EJECUCION_ID INT
	,DOMINIO_ID INT
	,ATRIBUTO_ID INT
	,DIMENSION_CALIDAD_ID INT
	,VERSION_ATRIBUTO VARCHAR(20)
	,REGISTROS_EVALUADOS BIGINT
	,REGISTROS_VALIDOS BIGINT
	,REGISTROS_INVALIDOS BIGINT
	,SCORE_DIMENSION_ATRIBUTO FLOAT
	,PESO_ATRIBUTO FLOAT
	,SCORE_ATRIBUTO_PONDERADO FLOAT
	,FECHA_CALCULO DATETIME
);


IF OBJECT_ID(N'CALIDAD.DQ_RESULTADO_DOMINIO', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.DQ_RESULTADO_DOMINIO;
END;
CREATE TABLE CALIDAD.DQ_RESULTADO_DOMINIO (
	RESULTADO_DOMINIO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	,EJECUCION_ID INT
	,DOMINIO_ID INT
	,DIMENSION_CALIDAD_ID INT
	,VERSION_DOMINIO VARCHAR(20)
	,REGISTROS_EVALUADOS BIGINT
	,REGISTROS_VALIDOS BIGINT
	,REGISTROS_INVALIDOS BIGINT
	,SCORE_DIMENSION_DOMINIO FLOAT
	,SCORE_DOMINIO_TOTAL FLOAT
	,FECHA_CALCULO DATETIME
);


IF OBJECT_ID(N'CALIDAD.DQ_RESULTADO_REGISTRO', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.DQ_RESULTADO_REGISTRO;
END;
CREATE TABLE CALIDAD.DQ_RESULTADO_REGISTRO (
	RESULTADO_REGISTRO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	,EJECUCION_ID INT
	,DOMINIO_ID INT
	,DIMENSION_CALIDAD_ID INT
	,SCORE_DIMENSION_REGISTRO FLOAT
	,FECHA_CALCULO DATETIME
);


IF OBJECT_ID(N'CALIDAD.DQ_EJECUCION', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.DQ_EJECUCION;
END;
CREATE TABLE CALIDAD.DQ_EJECUCION (
	EJECUCION_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	,TIPO_FLUJO VARCHAR(100)
	,FECHA_INICIO DATETIME
	,FECHA_FIN DATETIME
	,VENTANA_INICIO DATETIME
	,VENTANA_FIN DATETIME
	,ESTADO VARCHAR(15)
	,ORIGEN_DISPARO VARCHAR(100)
	,VERSION_CONFIGURACION VARCHAR
	,OBSERVACIONES VARCHAR(4000)
	,FECHA_REGISTRO DATETIME
	,USUARIO_REGISTRO VARCHAR(25)
);


IF OBJECT_ID(N'CALIDAD.DQ_EJECUCION_DOMINIO', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.DQ_EJECUCION_DOMINIO;
END;
CREATE TABLE CALIDAD.DQ_EJECUCION_DOMINIO (
	EJECUCION_ID INT
	,DOMINIO_ID INT
	,VERSION_DOMINIO VARCHAR(20)
	,REGISTROS_EVALUADOS BIGINT
	,REGISTROS_VALIDOS BIGINT
	,REGISTROS_INVALIDOS BIGINT
	,SCORE_DOMINIO FLOAT
	,ESTADO VARCHAR(15)
);
/**************************************************/
