/**************************************************/
/*
ALTER TABLE CALIDAD.DQ_DOMINIO
	ADD CONSTRAINT FK_CAT_SENSIBILIDAD_DOMINIO FOREIGN KEY (SENSIBILIDAD_ID) 
	REFERENCES CALIDAD.CAT_SENSIBILIDAD_ID(SENSIBILIDAD_ID);
*/
/*
ALTER TABLE CALIDAD.DQ_DOMINIO
	ADD CONSTRAINT FK_CAT_ESTCONCEPTUALIZACION_DOMINIO FOREIGN KEY (ESTADO_CONCEPTUALIZACION_ID) 
	REFERENCES CALIDAD.CAT_ESTADO_CONCEPTUALIZACION(ESTADO_CONCEPTUALIZACION_ID);
*/


ALTER TABLE CALIDAD.DQ_ATRIBUTO
	ADD CONSTRAINT FK_DOMINIO_ATRIBUTO FOREIGN KEY (DOMINIO_ID) 
	REFERENCES CALIDAD.DQ_DOMINIO(DOMINIO_ID);
/*
ALTER TABLE CALIDAD.DQ_ATRIBUTO
	ADD CONSTRAINT FK_CAT_SENSIBILIDAD_ATRIBUTO FOREIGN KEY (SENSIBILIDAD_ID) 
	REFERENCES CALIDAD.CAT_SENSIBILIDAD_ID(SENSIBILIDAD_ID);
*/
/*
ALTER TABLE CALIDAD.DQ_ATRIBUTO
	ADD CONSTRAINT FK_CAT_ESTCONCEPTUALIZACION_ATRIBUTO FOREIGN KEY (ESTADO_CONCEPTUALIZACION_ID) 
	REFERENCES CALIDAD.CAT_ESTADO_CONCEPTUALIZACION(ESTADO_CONCEPTUALIZACION_ID);
*/


ALTER TABLE CALIDAD.DQ_REGLA_ATRIBUTO
	ADD CONSTRAINT FK_DOMINIO_REGLAATRIBUTO FOREIGN KEY (DOMINIO_ID) 
	REFERENCES CALIDAD.DQ_DOMINIO(DOMINIO_ID);
ALTER TABLE CALIDAD.DQ_REGLA_ATRIBUTO
	ADD CONSTRAINT FK_ATRIBUTO_REGLAATRIBUTO FOREIGN KEY (ATRIBUTO_ID) 
	REFERENCES CALIDAD.DQ_ATRIBUTO(ATRIBUTO_ID);
ALTER TABLE CALIDAD.DQ_REGLA_ATRIBUTO
	ADD CONSTRAINT FK_CAT_DIMCALIDAD_REGLAATRIBUTO FOREIGN KEY (DIMENSION_CALIDAD_ID) 
	REFERENCES CALIDAD.CAT_DIMENSION_CALIDAD(DIMENSION_CALIDAD_ID);
/*
ALTER TABLE CALIDAD.DQ_REGLA_ATRIBUTO
	ADD CONSTRAINT FK_CAT_ESTCONCEPTUALIZACION_REGLAATRIBUTO FOREIGN KEY (ESTADO_CONCEPTUALIZACION_ID) 
	REFERENCES CALIDAD.CAT_ESTADO_CONCEPTUALIZACION(ESTADO_CONCEPTUALIZACION_ID);
*/


ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA
	ADD CONSTRAINT FK_EJECUCION_RESREGLA FOREIGN KEY (EJECUCION_ID) 
	REFERENCES CALIDAD.DQ_EJECUCION(EJECUCION_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA
	ADD CONSTRAINT FK_DOMINIO_RESREGLA FOREIGN KEY (DOMINIO_ID) 
	REFERENCES CALIDAD.DQ_DOMINIO(DOMINIO_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA
	ADD CONSTRAINT FK_ATRIBUTO_RESREGLA FOREIGN KEY (ATRIBUTO_ID) 
	REFERENCES CALIDAD.DQ_ATRIBUTO(ATRIBUTO_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA
	ADD CONSTRAINT FK_CAT_DIMCALIDAD_RESREGLA FOREIGN KEY (DIMENSION_CALIDAD_ID) 
	REFERENCES CALIDAD.CAT_DIMENSION_CALIDAD(DIMENSION_CALIDAD_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA
	ADD CONSTRAINT FK_CAT_REGLAATRIBUTO_RESREGLA FOREIGN KEY (REGLA_ID) 
	REFERENCES CALIDAD.DQ_REGLA_ATRIBUTO(REGLA_ID);
	

ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE
	ADD CONSTRAINT FK_EJECUCION_RESREGLADET FOREIGN KEY (EJECUCION_ID) 
	REFERENCES CALIDAD.DQ_EJECUCION(EJECUCION_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE
	ADD CONSTRAINT FK_DOMINIO_RESREGLADET FOREIGN KEY (DOMINIO_ID) 
	REFERENCES CALIDAD.DQ_DOMINIO(DOMINIO_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE
	ADD CONSTRAINT FK_ATRIBUTO_RESREGLADET FOREIGN KEY (ATRIBUTO_ID) 
	REFERENCES CALIDAD.DQ_ATRIBUTO(ATRIBUTO_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE
	ADD CONSTRAINT FK_CAT_DIMCALIDAD_RESREGLADET FOREIGN KEY (DIMENSION_CALIDAD_ID) 
	REFERENCES CALIDAD.CAT_DIMENSION_CALIDAD(DIMENSION_CALIDAD_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE
	ADD CONSTRAINT FK_CAT_REGLAATRIBUTO_RESREGLADET FOREIGN KEY (REGLA_ID) 
	REFERENCES CALIDAD.DQ_REGLA_ATRIBUTO(REGLA_ID);
	
	
ALTER TABLE CALIDAD.DQ_RESULTADO_DOMINIO
	ADD CONSTRAINT FK_EJECUCION_RESDOMINIO FOREIGN KEY (EJECUCION_ID) 
	REFERENCES CALIDAD.DQ_EJECUCION(EJECUCION_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_DOMINIO
	ADD CONSTRAINT FK_DOMINIO_RESDOMINIO FOREIGN KEY (DOMINIO_ID) 
	REFERENCES CALIDAD.DQ_DOMINIO(DOMINIO_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_DOMINIO
	ADD CONSTRAINT FK_CAT_DIMCALIDAD_RESDOMINIO FOREIGN KEY (DIMENSION_CALIDAD_ID) 
	REFERENCES CALIDAD.CAT_DIMENSION_CALIDAD(DIMENSION_CALIDAD_ID);


ALTER TABLE CALIDAD.DQ_RESULTADO_ATRIBUTO
	ADD CONSTRAINT FK_EJECUCION_RESATRIBUTO FOREIGN KEY (EJECUCION_ID) 
	REFERENCES CALIDAD.DQ_EJECUCION(EJECUCION_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_ATRIBUTO
	ADD CONSTRAINT FK_DOMINIO_RESATRIBUTO FOREIGN KEY (DOMINIO_ID) 
	REFERENCES CALIDAD.DQ_DOMINIO(DOMINIO_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_ATRIBUTO
	ADD CONSTRAINT FK_ATRIBUTO_RESATRIBUTO FOREIGN KEY (ATRIBUTO_ID) 
	REFERENCES CALIDAD.DQ_ATRIBUTO(ATRIBUTO_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_ATRIBUTO
	ADD CONSTRAINT FK_CAT_DIMCALIDAD_RESATRIBUTO FOREIGN KEY (DIMENSION_CALIDAD_ID) 
	REFERENCES CALIDAD.CAT_DIMENSION_CALIDAD(DIMENSION_CALIDAD_ID);

	
ALTER TABLE CALIDAD.DQ_RESULTADO_REGISTRO
	ADD CONSTRAINT FK_EJECUCION_RESREGISTRO FOREIGN KEY (EJECUCION_ID) 
	REFERENCES CALIDAD.DQ_EJECUCION(EJECUCION_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_REGISTRO
	ADD CONSTRAINT FK_DOMINIO_RESREGISTRO FOREIGN KEY (DOMINIO_ID) 
	REFERENCES CALIDAD.DQ_DOMINIO(DOMINIO_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_REGISTRO
	ADD CONSTRAINT FK_CAT_DIMCALIDAD_RESREGISTRO FOREIGN KEY (DIMENSION_CALIDAD_ID) 
	REFERENCES CALIDAD.CAT_DIMENSION_CALIDAD(DIMENSION_CALIDAD_ID);


ALTER TABLE CALIDAD.DQ_EJECUCION_DOMINIO
	ADD CONSTRAINT FK_EJECUCION_EJECDOMINIO FOREIGN KEY (EJECUCION_ID) 
	REFERENCES CALIDAD.DQ_EJECUCION(EJECUCION_ID);
ALTER TABLE CALIDAD.DQ_EJECUCION_DOMINIO
	ADD CONSTRAINT FK_DOMINIO_EJECDOMINIO FOREIGN KEY (DOMINIO_ID) 
	REFERENCES CALIDAD.DQ_DOMINIO(DOMINIO_ID);
/**************************************************/
