/**************************************************/
DELETE FROM CALIDAD.DQ_RESULTADO_REGISTRO;
DBCC CHECKIDENT ('CALIDAD.DQ_RESULTADO_REGISTRO', RESEED, 1);
DELETE FROM CALIDAD.DQ_EJECUCION;
DBCC CHECKIDENT ('CALIDAD.DQ_EJECUCION', RESEED, 1);
DELETE FROM CALIDAD.DQ_RESULTADO_REGLA_DETALLE;
DBCC CHECKIDENT ('CALIDAD.DQ_RESULTADO_REGLA_DETALLE', RESEED, 1);
DELETE FROM CALIDAD.DQ_RESULTADO_DOMINIO;
DBCC CHECKIDENT ('CALIDAD.DQ_RESULTADO_DOMINIO', RESEED, 1);
DELETE FROM CALIDAD.DQ_RESULTADO_ATRIBUTO;
DBCC CHECKIDENT ('CALIDAD.DQ_RESULTADO_ATRIBUTO', RESEED, 1);
DELETE FROM CALIDAD.DQ_REGLA_ATRIBUTO;
DBCC CHECKIDENT ('CALIDAD.DQ_REGLA_ATRIBUTO', RESEED, 1);
DELETE FROM CALIDAD.DQ_ATRIBUTO;
DBCC CHECKIDENT ('CALIDAD.DQ_ATRIBUTO', RESEED, 1);
DELETE FROM CALIDAD.DQ_DOMINIO;
DBCC CHECKIDENT ('CALIDAD.DQ_DOMINIO', RESEED, 1);
DELETE FROM CALIDAD.CAT_DIMENSION_CALIDAD;
DBCC CHECKIDENT ('CALIDAD.CAT_DIMENSION_CALIDAD', RESEED, 1);
/**************************************************/


/**************************************************/
INSERT INTO CALIDAD.DQ_DOMINIO VALUES ( 
	--NULL --DOMINIO_ID
	'Entidad Pública' --NOMBRE
	,NULL --TIPO_DOMINIO_ID
	,'Entidades públicas de Colombia' --DESCRIPCION
	,NULL --CONCEPTO_CLAVE_NEGOCIO
	,NULL --PROCESO_CLAVE_ASOCIADO
	,'Pública' --SENSIBILIDAD
	,NULL --KDE_NUM
	,1 --MCA_REGLAS_CALIDAD
	,'Conceptualizado' --ESTADO_CONCEPTUALIZACION
	,1 --PRIORIDAD
	,1 --OLA_IMPLEMENTACION
	,'2025-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

SELECT * FROM CALIDAD.DQ_DOMINIO;


INSERT INTO CALIDAD.DQ_ATRIBUTO VALUES (
	--NULL --ATRIBUTO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	1 --DOMINIO_ID
	,'EMAIL' --NOMBRE_TECNICO
	,'Correo electrónico de contacto con la Entidad Pública' --DESCRIPCION_FUNCIONAL
	,NULL --CONCEPTO_NEGOCIO
	,'VARCHAR' --TIPO_DATO
	,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$' --FORMATO
	,500 --LONGITUD
	,NULL --PRECISION
	,NULL --ESCALA
	,NULL --UNIDAD_MEDIDA
	,NULL --VALOR_DEFECTO
	,0 --MCA_OBLIGATORIO
	,0 --MCA_IDENTIFICADOR
	,0 --MCA_LLAVE_NEGOCIO
	,1 --MCA_KDE
	,1./6. --PESO_ATRIBUTO
	,NULL --CATALOGO_VALORES
	,'Pública' --SENSIBILIDAD
	,'Conceptualizado' --ESTADO_CONCEPTUALIZACION
	,'2015-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --FECHA_ULTIMO_CONTROL
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

SELECT * FROM CALIDAD.DQ_ATRIBUTO;


INSERT INTO CALIDAD.DQ_ATRIBUTO VALUES (
	--NULL --ATRIBUTO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	1 --DOMINIO_ID
	,'NOMBRE' --NOMBRE_TECNICO
	,'Nombre de la Entidad Pública' --DESCRIPCION_FUNCIONAL
	,NULL --CONCEPTO_NEGOCIO
	,'VARCHAR' --TIPO_DATO
	,'^[^a-z]+$' --FORMATO
	,500 --LONGITUD
	,NULL --PRECISION
	,NULL --ESCALA
	,NULL --UNIDAD_MEDIDA
	,NULL --VALOR_DEFECTO
	,1	--MCA_OBLIGATORIO
	,0 --MCA_IDENTIFICADOR
	,0 --MCA_LLAVE_NEGOCIO
	,1 --MCA_KDE
	,1./6. --PESO_ATRIBUTO
	,NULL --CATALOGO_VALORES
	,'Pública' --SENSIBILIDAD
	,'Conceptualizado' --ESTADO_CONCEPTUALIZACION
	,'2015-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --FECHA_ULTIMO_CONTROL
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_ATRIBUTO VALUES (
	--NULL --ATRIBUTO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	1 --DOMINIO_ID
	,'CCB_TELEFONO' --NOMBRE_TECNICO
	,'Teléfono de la Entidad Pública' --DESCRIPCION_FUNCIONAL
	,NULL --CONCEPTO_NEGOCIO
	,'VARCHAR' --TIPO_DATO
	,'^(\+)?(\(?\d+\)?)(([\s-]+)?(\d+)){0,}$' --FORMATO
	,500 --LONGITUD
	,NULL --PRECISION
	,NULL --ESCALA
	,NULL --UNIDAD_MEDIDA
	,NULL --VALOR_DEFECTO
	,0	--MCA_OBLIGATORIO
	,0 --MCA_IDENTIFICADOR
	,0 --MCA_LLAVE_NEGOCIO
	,1 --MCA_KDE
	,1./6. --PESO_ATRIBUTO
	,NULL --CATALOGO_VALORES
	,'Pública' --SENSIBILIDAD
	,'Conceptualizado' --ESTADO_CONCEPTUALIZACION
	,'2015-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --FECHA_ULTIMO_CONTROL
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_ATRIBUTO VALUES (
	--NULL --ATRIBUTO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	1 --DOMINIO_ID
	,'CCB_PAGINA_WEB' --NOMBRE_TECNICO
	,'Página web de la Entidad Pública' --DESCRIPCION_FUNCIONAL
	,NULL --CONCEPTO_NEGOCIO
	,'VARCHAR' --TIPO_DATO
	,'^(http|HTTP|https|HTTPS)?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&\/=]*)$' --FORMATO
	,500 --LONGITUD
	,NULL --PRECISION
	,NULL --ESCALA
	,NULL --UNIDAD_MEDIDA
	,NULL --VALOR_DEFECTO
	,0	--MCA_OBLIGATORIO
	,0 --MCA_IDENTIFICADOR
	,0 --MCA_LLAVE_NEGOCIO
	,1 --MCA_KDE
	,1./6. --PESO_ATRIBUTO
	,NULL --CATALOGO_VALORES
	,'Pública' --SENSIBILIDAD
	,'Conceptualizado' --ESTADO_CONCEPTUALIZACION
	,'2015-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --FECHA_ULTIMO_CONTROL
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_ATRIBUTO VALUES (
	--NULL --ATRIBUTO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	1 --DOMINIO_ID
	,'LATITUD' --NOMBRE_TECNICO
	,'Latitud de la Entidad Pública' --DESCRIPCION_FUNCIONAL
	,NULL --CONCEPTO_NEGOCIO
	,'NUMERIC' --TIPO_DATO
	,'^(-?[1-8]?\d(?:\.\d{1,18})?|90(?:\.0{1,18})?)$' --FORMATO
	,NULL --LONGITUD
	,10 --PRECISION
	,7 --ESCALA
	,NULL --UNIDAD_MEDIDA
	,NULL --VALOR_DEFECTO
	,0	--MCA_OBLIGATORIO
	,0 --MCA_IDENTIFICADOR
	,0 --MCA_LLAVE_NEGOCIO
	,1 --MCA_KDE
	,1./6. --PESO_ATRIBUTO
	,NULL --CATALOGO_VALORES
	,'Pública' --SENSIBILIDAD
	,'Conceptualizado' --ESTADO_CONCEPTUALIZACION
	,'2015-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --FECHA_ULTIMO_CONTROL
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_ATRIBUTO VALUES (
	--NULL --ATRIBUTO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	1 --DOMINIO_ID
	,'LONGITUD' --NOMBRE_TECNICO
	,'Longitud de la Entidad Pública' --DESCRIPCION_FUNCIONAL
	,NULL --CONCEPTO_NEGOCIO
	,'NUMERIC' --TIPO_DATO
	,'^(-?(?:1[0-7]|[1-9])?\d(?:\.\d{1,18})?|180(?:\.0{1,18})?)$' --FORMATO
	,NULL --LONGITUD
	,10 --PRECISION
	,7 --ESCALA
	,NULL --UNIDAD_MEDIDA
	,NULL --VALOR_DEFECTO
	,0	--MCA_OBLIGATORIO
	,0 --MCA_IDENTIFICADOR
	,0 --MCA_LLAVE_NEGOCIO
	,1 --MCA_KDE
	,1./6. --PESO_ATRIBUTO
	,NULL --CATALOGO_VALORES
	,'Pública' --SENSIBILIDAD
	,'Conceptualizado' --ESTADO_CONCEPTUALIZACION
	,'2015-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --FECHA_ULTIMO_CONTROL
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_ATRIBUTO VALUES (
	--NULL --ATRIBUTO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	1 --DOMINIO_ID
	,'DM_INSTITUCION_COD_INSTITUCION' --NOMBRE_TECNICO
	,'Código único de identificación de la Entidad Pública' --DESCRIPCION_FUNCIONAL
	,NULL --CONCEPTO_NEGOCIO
	,'VARCHAR' --TIPO_DATO
	,NULL --FORMATO
	,500 --LONGITUD
	,NULL --PRECISION
	,NULL --ESCALA
	,NULL --UNIDAD_MEDIDA
	,NULL --VALOR_DEFECTO
	,1	--MCA_OBLIGATORIO
	,1 --MCA_IDENTIFICADOR
	,1 --MCA_LLAVE_NEGOCIO
	,1 --MCA_KDE
	,1./6. --PESO_ATRIBUTO
	,NULL --CATALOGO_VALORES
	,'Pública' --SENSIBILIDAD
	,'Conceptualizado' --ESTADO_CONCEPTUALIZACION
	,'2015-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --FECHA_ULTIMO_CONTROL
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

SELECT * FROM CALIDAD.DQ_ATRIBUTO;


INSERT INTO CALIDAD.CAT_DIMENSION_CALIDAD VALUES (
	--NULL -- DIMENSION_CALIDAD_ID
	'Validez' --NOMBRE
	,'Grado en que los datos se ajustan en contenido a un valor aceptable en el dominio de la variable o que satisfacen el formato establecido.' --DEFINICION
	,'activo' --ESTADO
);

INSERT INTO CALIDAD.CAT_DIMENSION_CALIDAD VALUES (
	--NULL -- DIMENSION_CALIDAD_ID
	'Completitud' --NOMBRE
	,'Grado en que se permite que los datos sean poblados o no con un valor.' --DEFINICION
	,'activo' --ESTADO
);

INSERT INTO CALIDAD.CAT_DIMENSION_CALIDAD VALUES (
	--NULL -- DIMENSION_CALIDAD_ID
	'Unicidad' --NOMBRE
	,'Grado en el que los datos pueden estar repetidos o no dentro del mismo sistema.' --DEFINICION
	,'activo' --ESTADO
);

INSERT INTO CALIDAD.CAT_DIMENSION_CALIDAD VALUES (
	--NULL -- DIMENSION_CALIDAD_ID
	'Oportunidad' --NOMBRE
	,'Grado en el que los datos están actualizados y son consistentes con el evento de negocio más reciente.' --DEFINICION
	,'activo' --ESTADO
);

INSERT INTO CALIDAD.CAT_DIMENSION_CALIDAD VALUES (
	--NULL -- DIMENSION_CALIDAD_ID
	'Precisión' --NOMBRE
	,'Grado en que los datos son consistentes con la realidad o con una fuente autorizada de confianza o de referencia.' --DEFINICION
	,'activo' --ESTADO
);

INSERT INTO CALIDAD.CAT_DIMENSION_CALIDAD VALUES (
	--NULL -- DIMENSION_CALIDAD_ID
	'Lógica' --NOMBRE
	,'Grado en que los datos se ajustan a las pruebas de razonabilidad del negocio, basadas en escenarios del mundo real y valores de otros datos.' --DEFINICION
	,'activo' --ESTADO
);

INSERT INTO CALIDAD.CAT_DIMENSION_CALIDAD VALUES (
	--NULL -- DIMENSION_CALIDAD_ID
	'Cobertura' --NOMBRE
	,'Grado en que los datos están incluidos en todas las aplicaciones y sistemas de soporte al negocio que los requieren.' --DEFINICION
	,'activo' --ESTADO
);

INSERT INTO CALIDAD.CAT_DIMENSION_CALIDAD VALUES (
	--NULL -- DIMENSION_CALIDAD_ID
	'Integridad' --NOMBRE
	,'Grado en que los datos conservan un contenido consistente a través de los diferentes almacenes de datos.' --DEFINICION
	,'activo' --ESTADO
);

SELECT * FROM CALIDAD.CAT_DIMENSION_CALIDAD;


INSERT INTO CALIDAD.DQ_REGLA_ATRIBUTO VALUES (
	--NULL --REGLA_ID
	1 --DOMINIO_ID
	,1 --ATRIBUTO_ID
	,1 --DIMENSION_CALIDAD_ID
	,'El correo electrónico debe tener un formato válido' --DESCRIPCION_REGLA
	,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$' --EXPRESION_REGULAR
	,0.8 --UMBRAL_MINIMO
	,0.05 --MARGEN_TOLERANCIA
	,0 --ES_CRITICA_GATING
	,0.5 --PESO_REGLA
	,CURRENT_USER --RESPONSABLE
	,'activo' -- ESTADO
	,'2025-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_REGLA_ATRIBUTO VALUES (
	--NULL --REGLA_ID
	1 --DOMINIO_ID
	,1 --ATRIBUTO_ID
	,2 --DIMENSION_CALIDAD_ID
	,'El correo electrónico no puede estar vacío' --DESCRIPCION_REGLA
	,'.+' --EXPRESION_REGULAR
	,0.8 --UMBRAL_MINIMO
	,0.05 --MARGEN_TOLERANCIA
	,0 --ES_CRITICA_GATING
	,0.5 --PESO_REGLA
	,CURRENT_USER --RESPONSABLE
	,'activo' -- ESTADO
	,'2025-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_REGLA_ATRIBUTO VALUES (
	--NULL --REGLA_ID
	1 --DOMINIO_ID
	,2 --ATRIBUTO_ID
	,1 --DIMENSION_CALIDAD_ID
	,'El nombre de la entidad debe estar en mayúsculas sostenidas' --DESCRIPCION_REGLA
	,'^[^a-z]+$' --EXPRESION_REGULAR
	,0.8 --UMBRAL_MINIMO
	,0.05 --MARGEN_TOLERANCIA
	,0 --ES_CRITICA_GATING
	,0.5 --PESO_REGLA
	,CURRENT_USER --RESPONSABLE
	,'activo' -- ESTADO
	,'2025-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_REGLA_ATRIBUTO VALUES (
	--NULL --REGLA_ID
	1 --DOMINIO_ID
	,2 --ATRIBUTO_ID
	,2 --DIMENSION_CALIDAD_ID
	,'El nombre de la entidad no puede estar vacío' --DESCRIPCION_REGLA
	,'.+' --EXPRESION_REGULAR
	,0.8 --UMBRAL_MINIMO
	,0.05 --MARGEN_TOLERANCIA
	,0 --ES_CRITICA_GATING
	,0.5 --PESO_REGLA
	,CURRENT_USER --RESPONSABLE
	,'activo' -- ESTADO
	,'2025-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_REGLA_ATRIBUTO VALUES (
	--NULL --REGLA_ID
	1 --DOMINIO_ID
	,3 --ATRIBUTO_ID
	,1 --DIMENSION_CALIDAD_ID
	,'El teléfono de la entidad debe tener un formato válido' --DESCRIPCION_REGLA
	,'^(\+)?(\(?\d+\)?)(([\s-]+)?(\d+)){0,}$' --EXPRESION_REGULAR
	,0.8 --UMBRAL_MINIMO
	,0.05 --MARGEN_TOLERANCIA
	,0 --ES_CRITICA_GATING
	,1 --PESO_REGLA
	,CURRENT_USER --RESPONSABLE
	,'activo' -- ESTADO
	,'2025-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_REGLA_ATRIBUTO VALUES (
	--NULL --REGLA_ID
	1 --DOMINIO_ID
	,4 --ATRIBUTO_ID
	,1 --DIMENSION_CALIDAD_ID
	,'La página web de la entidad debe tener un formato válido' --DESCRIPCION_REGLA
	,'^(http|HTTP|https|HTTPS)?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&\/=]*)$' --EXPRESION_REGULAR
	,0.8 --UMBRAL_MINIMO
	,0.05 --MARGEN_TOLERANCIA
	,0 --ES_CRITICA_GATING
	,1 --PESO_REGLA
	,CURRENT_USER --RESPONSABLE
	,'activo' -- ESTADO
	,'2025-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_REGLA_ATRIBUTO VALUES (
	--NULL --REGLA_ID
	1 --DOMINIO_ID
	,5 --ATRIBUTO_ID
	,1 --DIMENSION_CALIDAD_ID
	,'La latitud de la entidad debe tener un formato válido' --DESCRIPCION_REGLA
	,'^(-?[1-8]?\d(?:\.\d{1,18})?|90(?:\.0{1,18})?)$' --EXPRESION_REGULAR
	,0.8 --UMBRAL_MINIMO
	,0.05 --MARGEN_TOLERANCIA
	,0 --ES_CRITICA_GATING
	,1 --PESO_REGLA
	,CURRENT_USER --RESPONSABLE
	,'activo' -- ESTADO
	,'2025-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_REGLA_ATRIBUTO VALUES (
	--NULL --REGLA_ID
	1 --DOMINIO_ID
	,6 --ATRIBUTO_ID
	,1 --DIMENSION_CALIDAD_ID
	,'La longitud de la entidad debe tener un formato válido' --DESCRIPCION_REGLA
	,'^(-?(?:1[0-7]|[1-9])?\d(?:\.\d{1,18})?|180(?:\.0{1,18})?)$' --EXPRESION_REGULAR
	,0.8 --UMBRAL_MINIMO
	,0.05 --MARGEN_TOLERANCIA
	,0 --ES_CRITICA_GATING
	,1 --PESO_REGLA
	,CURRENT_USER --RESPONSABLE
	,'activo' -- ESTADO
	,'2025-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

SELECT * FROM CALIDAD.DQ_REGLA_ATRIBUTO;
/**************************************************/