CREATE PROCEDURE CALIDAD.GESTION_EJECUCION
--ALTER PROCEDURE CALIDAD.GESTION_EJECUCION
(
    @EJECUCION_ID_ENTRADA INT = NULL,
	@ESTADO_EJECUCION VARCHAR(15) = NULL,
	@OBSERVACIONES VARCHAR(4000) = NULL,
    @EJECUCION_ID_SALIDA INT OUTPUT
)
AS
/*
-- =============================================
-- Author:      Mary Luz Perdomo Cruz
-- Create Date: 2025-11-28
-- Description: Realizar la creación / actualización del registro de ejecución
-- =============================================
*/
BEGIN
    SET NOCOUNT ON
	-- Variable para almacenar la consulta dimánica que realiza el perfilamiento
	DECLARE @CONSULTA_SQL NVARCHAR(4000)
	DECLARE @CONTEO_EJECUCION_ID INT
	-- Validar si el registro de ejecución existe
	IF @EJECUCION_ID_ENTRADA IS NOT NULL
	BEGIN
		SELECT @CONTEO_EJECUCION_ID = COUNT(EJECUCION_ID) FROM CALIDAD.DQ_EJECUCION WHERE EJECUCION_ID = @EJECUCION_ID_ENTRADA
	END
	
	IF @CONTEO_EJECUCION_ID = 0 OR @EJECUCION_ID_ENTRADA IS NULL
	BEGIN
		INSERT INTO CALIDAD.DQ_EJECUCION VALUES (
			--NULL --EJECUCION_ID
			'BATCH' --TIPO_FLUJO
			,CURRENT_TIMESTAMP --FECHA_INICIO
			,NULL --FECHA_FIN
			,NULL --VENTANA_INICIO
			,NULL --VENTANA_FIN
			,'iniciado' --ESTADO
			,'programado' --ORIGEN_DISPARO
			,'1' --VERSION_CONFIGURACION
			,NULL --OBSERVACIONES
			,CURRENT_TIMESTAMP --FECHA_REGISTRO
			,CURRENT_USER --USUARIO_REGISTRO
		)
		SET @EJECUCION_ID_SALIDA = SCOPE_IDENTITY()
	END
	ELSE
	BEGIN
		UPDATE CALIDAD.DQ_EJECUCION 
		SET 
			FECHA_FIN = CURRENT_TIMESTAMP
			,ESTADO = @ESTADO_EJECUCION
			,OBSERVACIONES = @OBSERVACIONES
		WHERE EJECUCION_ID = @EJECUCION_ID_ENTRADA
		SET @EJECUCION_ID_SALIDA = @EJECUCION_ID_ENTRADA
	END
END;
GO;


CREATE PROCEDURE CALIDAD.EJECUCION
--ALTER PROCEDURE CALIDAD.EJECUCION
(
    @EJECUCION_ID INT OUTPUT
)
AS
/*
-- =============================================
-- Author:      Mary Luz Perdomo Cruz
-- Create Date: 2025-11-28
-- Description: Ejecutar el proceso de calidad
-- =============================================
*/
BEGIN
    SET NOCOUNT ON
	-- Variable para almacenar la consulta dimánica que realiza el perfilamiento
	DECLARE @CONSULTA_SQL NVARCHAR(4000)
	DECLARE @ID_EJECUCION_LOCAL INT
	
	BEGIN TRY
		
		-- Crear un nuevo registro de ejecución
		EXEC CALIDAD.GESTION_EJECUCION @EJECUCION_ID_ENTRADA = @EJECUCION_ID, @EJECUCION_ID_SALIDA = @ID_EJECUCION_LOCAL OUTPUT
		
		-- Calcular el resultado de calidad a nivel de regla-detalle
		DECLARE CUR_CONSULTAS CURSOR LOCAL FOR
			--Generador de consultas dinámicas
			SELECT
				'--dinamyc sql
				WITH VALIDACION AS (
						SELECT 
							'+STR(@ID_EJECUCION_LOCAL)+' AS EJECUCION_ID
							,A.DOMINIO_ID AS DOMINIO_ID
							,A.ATRIBUTO_ID AS ATRIBUTO_ID
							,R.REGLA_ID AS REGLA_ID
							,R.DIMENSION_CALIDAD_ID AS DIMENSION_CALIDAD_ID
							,SRC.DM_INSTITUCION_COD_INSTITUCION AS ID_REGISTRO_FUENTE
							,REGEXP_COUNT( TRIM( COALESCE( SRC.'+C.COLUMN_NAME+', '''' ) ), R.EXPRESION_REGULAR ) AS RESULTADO_VALIDACION
							,TRIM( COALESCE( SRC.'+C.COLUMN_NAME+', '''' ) ) AS VALOR_OBSERVADO
						FROM CALIDAD.DQ_REGLA_ATRIBUTO AS R
						LEFT JOIN CALIDAD.DQ_ATRIBUTO AS A 
							ON R.ATRIBUTO_ID = A.ATRIBUTO_ID 
						CROSS JOIN FUENTE.ENTIDAD_PUBLICA_COLOMBIA AS SRC
						WHERE 1 = 1
							AND A.NOMBRE_TECNICO = '''+C.COLUMN_NAME+'''
				)
				INSERT INTO CALIDAD.DQ_RESULTADO_REGLA_DETALLE
				SELECT
					EJECUCION_ID
					,DOMINIO_ID
					,ATRIBUTO_ID
					,REGLA_ID
					,DIMENSION_CALIDAD_ID
					,ID_REGISTRO_FUENTE
					,VALOR_OBSERVADO
					/*,CASE 
						WHEN RESULTADO_VALIDACION IS NULL THEN -1 
						WHEN RESULTADO_VALIDACION >= 1 THEN 0 
						WHEN RESULTADO_VALIDACION = 0 THEN 1 
						ELSE -2 
					END AS RESULTADO*/
					,CASE 
						WHEN RESULTADO_VALIDACION IS NULL THEN ''No aplica''
						WHEN RESULTADO_VALIDACION >= 1 THEN ''CUMPLE'' 
						WHEN RESULTADO_VALIDACION = 0 THEN ''NO CUMPLE''
						ELSE ''<<OTRO>>'' 
					END
					,NULL
					,NULL
					,CURRENT_TIMESTAMP
				FROM VALIDACION;
				' AS SQL_TXT
			FROM information_schema.tables AS T
			JOIN information_schema.COLUMNS AS C
			ON T.TABLE_CATALOG = C.TABLE_CATALOG
				AND T.TABLE_SCHEMA = C.TABLE_SCHEMA
				AND T.TABLE_NAME = C.TABLE_NAME
			WHERE 1 = 1
				AND T.TABLE_SCHEMA = 'FUENTE'
				AND T.TABLE_NAME = 'ENTIDAD_PUBLICA_COLOMBIA'

		-- Limpiar ejecuciones previas con la misma fecha
		DELETE FROM CALIDAD.DQ_RESULTADO_REGLA_DETALLE WHERE EJECUCION_ID = @ID_EJECUCION_LOCAL

		-- Abrir el cursor
		OPEN CUR_CONSULTAS
		-- Traer el primer registro
		FETCH NEXT FROM CUR_CONSULTAS INTO @CONSULTA_SQL
		-- Recorrer el cursor mientras sea posible
		WHILE @@FETCH_STATUS = 0
		BEGIN
			-- Ejecutar la consulta dinámica
			--PRINT 'consulta: ' + @CONSULTA_SQL;
			EXEC sp_executesql @CONSULTA_SQL
			-- Traer el siguiente registro
			FETCH NEXT FROM CUR_CONSULTAS INTO @CONSULTA_SQL
		END
		-- Cerrar el cursos
		CLOSE CUR_CONSULTAS
		-- Eliminar el cursor
		DEALLOCATE CUR_CONSULTAS

		
		-- Calcular el resultado de calidad a nivel de regla
		-- Limpiar ejecuciones previas con la misma fecha
		DELETE FROM CALIDAD.DQ_RESULTADO_REGLA WHERE EJECUCION_ID = @ID_EJECUCION_LOCAL
		
		SET @CONSULTA_SQL = '
		WITH RESULTADO_X_REGLA AS (
			SELECT
				RD.EJECUCION_ID
				,RD.DOMINIO_ID
				,RD.ATRIBUTO_ID
				,RD.REGLA_ID
				,RD.DIMENSION_CALIDAD_ID
				,COUNT(1) AS REGISTROS_EVALUADOS
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''CUMPLE'' THEN 1 ELSE 0 END ) AS REGISTROS_CUMPLE
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''PARCIAL'' THEN 1 ELSE 0 END ) AS REGISTROS_CUMPLE_PARCIAL
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''NO CUMPLE'' THEN 1 ELSE 0 END ) AS REGISTROS_NO_CUMPLE
				,R.UMBRAL_MINIMO
				,R.MARGEN_TOLERANCIA
				,R.PESO_REGLA
			FROM CALIDAD.DQ_RESULTADO_REGLA_DETALLE AS RD
			LEFT JOIN CALIDAD.DQ_REGLA_ATRIBUTO AS R
				ON RD.REGLA_ID = R.REGLA_ID
			WHERE EJECUCION_ID = '+STR(@ID_EJECUCION_LOCAL)+'
			GROUP BY RD.EJECUCION_ID
				,RD.DOMINIO_ID
				,RD.ATRIBUTO_ID
				,RD.REGLA_ID
				,RD.DIMENSION_CALIDAD_ID
				,R.UMBRAL_MINIMO
				,R.MARGEN_TOLERANCIA
				,R.PESO_REGLA
		)
		INSERT INTO CALIDAD.DQ_RESULTADO_REGLA
		SELECT
			--NULL --RESULTADO_REGLA_ID
			RXR.EJECUCION_ID --EJECUCION_ID
			,RXR.DOMINIO_ID --DOMINIO_ID
			,RXR.ATRIBUTO_ID --ATRIBUTO_ID 
			,RXR.REGLA_ID --REGLA_ID
			,RXR.DIMENSION_CALIDAD_ID --DIMENSION_CALIDAD_ID
			,RXR.REGISTROS_EVALUADOS
			,RXR.REGISTROS_CUMPLE
			,RXR.REGISTROS_CUMPLE_PARCIAL
			,RXR.REGISTROS_NO_CUMPLE
			,RXR.REGISTROS_CUMPLE / ( RXR.REGISTROS_EVALUADOS * 1. ) --TASA_CUMPLIMIENTO
			,RXR.REGISTROS_NO_CUMPLE / ( RXR.REGISTROS_EVALUADOS * 1. ) --TASA_ERROR
			,RXR.UMBRAL_MINIMO --UMBRAL_MINIMO
			,RXR.MARGEN_TOLERANCIA --MARGEN_TOLERANCIA
			,CASE 
				WHEN RXR.REGISTROS_CUMPLE / ( RXR.REGISTROS_EVALUADOS * 1. ) < RXR.UMBRAL_MINIMO - RXR.MARGEN_TOLERANCIA THEN 0 
				ELSE 1 
			END --MCA_UMBRAL_CUMPLIDO
			,RXR.PESO_REGLA
			,( RXR.REGISTROS_CUMPLE / ( RXR.REGISTROS_EVALUADOS * 1. ) ) * RXR.PESO_REGLA --SCORE_REGLA
			,CURRENT_TIMESTAMP --FECHA_CALCULO
		FROM RESULTADO_X_REGLA AS RXR
		'
		EXEC sp_executesql @CONSULTA_SQL
		
		-- Calcular el resultado de calidad a nivel de atributo
		-- Limpiar ejecuciones previas con la misma fecha
		DELETE FROM CALIDAD.DQ_RESULTADO_ATRIBUTO WHERE EJECUCION_ID = @ID_EJECUCION_LOCAL
		
		SET @CONSULTA_SQL = '
		WITH RESULTADO_X_ATRIBUTO AS (
			SELECT
				RD.EJECUCION_ID
				,RD.DOMINIO_ID
				,RD.ATRIBUTO_ID
				,RD.DIMENSION_CALIDAD_ID
				,COUNT(1) AS REGISTROS_EVALUADOS
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''CUMPLE'' THEN 1 ELSE 0 END ) AS REGISTROS_VALIDOS
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''NO CUMPLE'' THEN 1 ELSE 0 END ) AS REGISTROS_INVALIDOS
				,A.PESO_ATRIBUTO
			FROM CALIDAD.DQ_RESULTADO_REGLA_DETALLE AS RD
			LEFT JOIN CALIDAD.DQ_ATRIBUTO AS A
				ON RD.ATRIBUTO_ID = A.ATRIBUTO_ID
			WHERE EJECUCION_ID = '+STR(@ID_EJECUCION_LOCAL)+'
			GROUP BY RD.EJECUCION_ID
				,RD.DOMINIO_ID
				,RD.ATRIBUTO_ID
				,RD.DIMENSION_CALIDAD_ID
				,A.PESO_ATRIBUTO
		)
		INSERT INTO CALIDAD.DQ_RESULTADO_ATRIBUTO
		SELECT
			--NULL --RESULTADO_ATRIBUTO_ID
			RXA.EJECUCION_ID --EJECUCION_ID
			,RXA.DOMINIO_ID --DOMINIO_ID
			,RXA.ATRIBUTO_ID --ATRIBUTO_ID 
			,RXA.DIMENSION_CALIDAD_ID --DIMENSION_CALIDAD_ID
			,''1'' --VERSION_ATRIBUTO
			,RXA.REGISTROS_EVALUADOS --REGISTROS_EVALUADOS
			,RXA.REGISTROS_VALIDOS --REGISTROS_VALIDOS
			,RXA.REGISTROS_INVALIDOS --REGISTROS_INVALIDOS
			,RXA.REGISTROS_VALIDOS / ( RXA.REGISTROS_EVALUADOS * 1. ) --SCORE_DIMENSION_ATRIBUTO
			,RXA.PESO_ATRIBUTO --PESO_ATRIBUTO
			,( RXA.REGISTROS_VALIDOS / ( RXA.REGISTROS_EVALUADOS * 1. ) ) * RXA.PESO_ATRIBUTO --SCORE_ATRIBUTO_PONDERADO
			,CURRENT_TIMESTAMP --FECHA_CALCULO
		FROM RESULTADO_X_ATRIBUTO AS RXA
		'
		EXEC sp_executesql @CONSULTA_SQL
		
		-- Calcular el resultado de calidad a nivel de dominio
		-- Limpiar ejecuciones previas con la misma fecha
		DELETE FROM CALIDAD.DQ_RESULTADO_DOMINIO WHERE EJECUCION_ID = @ID_EJECUCION_LOCAL
		
		SET @CONSULTA_SQL = '
		WITH RESULTADO_X_DOMINIO_DIM AS (
			SELECT
				RD.EJECUCION_ID
				,RD.DOMINIO_ID
				,RD.DIMENSION_CALIDAD_ID
				,COUNT(1) AS REGISTROS_EVALUADOS
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''CUMPLE'' THEN 1 ELSE 0 END ) AS REGISTROS_VALIDOS
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''NO CUMPLE'' THEN 1 ELSE 0 END ) AS REGISTROS_INVALIDOS
			FROM CALIDAD.DQ_RESULTADO_REGLA_DETALLE AS RD
			WHERE EJECUCION_ID = '+STR(@ID_EJECUCION_LOCAL)+'
			GROUP BY RD.EJECUCION_ID
				,RD.DOMINIO_ID
				,RD.DIMENSION_CALIDAD_ID
		), RESULTADO_X_DOMINIO AS (
		SELECT
				RD.EJECUCION_ID
				,RD.DOMINIO_ID
				,COUNT(1) AS REGISTROS_EVALUADOS
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''CUMPLE'' THEN 1 ELSE 0 END ) AS REGISTROS_VALIDOS
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''NO CUMPLE'' THEN 1 ELSE 0 END ) AS REGISTROS_INVALIDOS
			FROM CALIDAD.DQ_RESULTADO_REGLA_DETALLE AS RD
			WHERE EJECUCION_ID = '+STR(@ID_EJECUCION_LOCAL)+'
			GROUP BY RD.EJECUCION_ID
				,RD.DOMINIO_ID
		)
		INSERT INTO CALIDAD.DQ_RESULTADO_DOMINIO
		SELECT
			--NULL --RESULTADO_DOMINIO_ID
			RXDD.EJECUCION_ID --EJECUCION_ID
			,RXDD.DOMINIO_ID --DOMINIO_ID
			,RXDD.DIMENSION_CALIDAD_ID --DIMENSION_CALIDAD_ID
			,''1'' --VERSION_DOMINIO
			,RXDD.REGISTROS_EVALUADOS --REGISTROS_EVALUADOS
			,RXDD.REGISTROS_VALIDOS --REGISTROS_VALIDOS
			,RXDD.REGISTROS_INVALIDOS --REGISTROS_INVALIDOS
			,RXDD.REGISTROS_VALIDOS / ( RXDD.REGISTROS_EVALUADOS * 1. ) --SCORE_DIMENSION_DOMINIO
			,RXD.REGISTROS_VALIDOS / ( RXD.REGISTROS_EVALUADOS * 1. ) --SCORE_DOMINIO_TOTAL
			,CURRENT_TIMESTAMP --FECHA_CALCULO
		FROM RESULTADO_X_DOMINIO_DIM AS RXDD
		LEFT JOIN RESULTADO_X_DOMINIO AS RXD
		ON RXDD.EJECUCION_ID = RXD.EJECUCION_ID
		AND RXDD.DOMINIO_ID = RXD.DOMINIO_ID

		'
		EXEC sp_executesql @CONSULTA_SQL
		
		-- Calcular el resultado de la ejecución a nivel de dominio
		-- Limpiar ejecuciones previas con la misma fecha
		DELETE FROM CALIDAD.DQ_EJECUCION_DOMINIO WHERE EJECUCION_ID = @ID_EJECUCION_LOCAL
		
		SET @CONSULTA_SQL = '
		WITH RESULTADO_X_DOMINIO AS (
			SELECT
				RD.EJECUCION_ID
				,RD.DOMINIO_ID
				,COUNT(1) AS REGISTROS_EVALUADOS
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''CUMPLE'' THEN 1 ELSE 0 END ) AS REGISTROS_VALIDOS
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''NO CUMPLE'' THEN 1 ELSE 0 END ) AS REGISTROS_INVALIDOS
			FROM CALIDAD.DQ_RESULTADO_REGLA_DETALLE AS RD
			WHERE EJECUCION_ID = '+STR(@ID_EJECUCION_LOCAL)+'
			GROUP BY RD.EJECUCION_ID
				,RD.DOMINIO_ID
		)
		INSERT INTO CALIDAD.DQ_EJECUCION_DOMINIO
		SELECT
			RXD.EJECUCION_ID --EJECUCION_ID
			,RXD.DOMINIO_ID --DOMINIO_ID
			,''1'' --VERSION_DOMINIO
			,RXD.REGISTROS_EVALUADOS --REGISTROS_EVALUADOS
			,RXD.REGISTROS_VALIDOS --REGISTROS_VALIDOS
			,RXD.REGISTROS_INVALIDOS --REGISTROS_INVALIDOS
			,RXD.REGISTROS_VALIDOS / ( RXD.REGISTROS_EVALUADOS * 1. ) --SCORE_DOMINIO
			,''finalizado'' --ESTADO
		FROM RESULTADO_X_DOMINIO AS RXD
		'
		EXEC sp_executesql @CONSULTA_SQL
		
		-- Actualizar el registro de ejecución
		EXEC CALIDAD.GESTION_EJECUCION @EJECUCION_ID_ENTRADA = @ID_EJECUCION_LOCAL, @ESTADO_EJECUCION = 'finalizado', @EJECUCION_ID_SALIDA = @ID_EJECUCION_LOCAL OUTPUT
	END TRY
	BEGIN CATCH
		DECLARE @MENSAJE_ERROR VARCHAR(4000)
		SET @MENSAJE_ERROR = 'Error'+STR(ERROR_NUMBER())+': '+ERROR_MESSAGE()
		EXEC CALIDAD.GESTION_EJECUCION @EJECUCION_ID_ENTRADA = @ID_EJECUCION_LOCAL, @ESTADO_EJECUCION = 'error', @OBSERVACIONES = @MENSAJE_ERROR, @EJECUCION_ID_SALIDA = @ID_EJECUCION_LOCAL OUTPUT
	END CATCH;
	
	SET @EJECUCION_ID = @ID_EJECUCION_LOCAL
END;
GO;
