DECLARE @EJECUCION_ID INT;
SET @EJECUCION_ID = NULL;
EXEC CALIDAD.EJECUCION @EJECUCION_ID = @EJECUCION_ID OUTPUT;
SELECT COUNT(1) FROM CALIDAD.DQ_RESULTADO_REGLA_DETALLE WHERE EJECUCION_ID = @EJECUCION_ID;
SELECT COUNT(1) FROM CALIDAD.DQ_RESULTADO_REGLA WHERE EJECUCION_ID = @EJECUCION_ID;
SELECT COUNT(1) FROM CALIDAD.DQ_RESULTADO_ATRIBUTO WHERE EJECUCION_ID = @EJECUCION_ID;
SELECT COUNT(1) FROM CALIDAD.DQ_RESULTADO_DOMINIO WHERE EJECUCION_ID = @EJECUCION_ID;
SELECT COUNT(1) FROM CALIDAD.DQ_EJECUCION_DOMINIO WHERE EJECUCION_ID = @EJECUCION_ID;
SELECT * FROM CALIDAD.DQ_EJECUCION WHERE EJECUCION_ID = @EJECUCION_ID;
