/**************************************************/
IF OBJECT_ID(N'FUENTE.ENTIDAD_PUBLICA_COLOMBIA', N'U') IS NOT NULL
BEGIN
	DROP TABLE FUENTE.ENTIDAD_PUBLICA_COLOMBIA;
END;
CREATE TABLE FUENTE.ENTIDAD_PUBLICA_COLOMBIA (
    DM_INSTITUCION_COD_INSTITUCION VARCHAR(500)
	,NOMBRE VARCHAR(500)
	,CCB_NIT_INST VARCHAR(500)
	,ORDEN VARCHAR(500)
	,SUBORDEN VARCHAR(500)
	,NIVEL_INSTITUCION VARCHAR(500)
	,CLASIFICACION_ORGANICA VARCHAR(500)
	,SECTOR VARCHAR(500)
	,NATURALEZA_JURIDICA VARCHAR(500)
	,TIPO_INSTITUCION VARCHAR(500)
	,IDMUNICIPIO VARCHAR(500)
	,MUNICIPIO VARCHAR(500)
	,IDDEPARTAMENTO VARCHAR(500)
	,DEPARTAMENTO VARCHAR(500)
	,DIRECCION VARCHAR(500)
	,FAX VARCHAR(500)
	,EMAIL VARCHAR(500)
	,CCB_TELEFONO VARCHAR(500)
	,CCB_PAGINA_WEB VARCHAR(500)
	,LONGITUD VARCHAR(500)
	,LATITUD VARCHAR(500)
	,ESTADO_INS VARCHAR(500)
	,NOMBRE_REPRESENTANTE VARCHAR(500)
	,CARGO_REPRESENTANTE VARCHAR(500)
);
/**************************************************/