/**************************************************/
IF SCHEMA_ID('CALIDAD') IS NULL
BEGIN
	--CREATE SCHEMA CALIDAD;
	SELECT 1;
END;
/**************************************************/


/**************************************************/
IF OBJECT_ID(N'CALIDAD.DQ_DOMINIO', N'U') IS NOT NULL
BEGIN
	--ALTER TABLE CALIDAD.DQ_DOMINIO DROP CONSTRAINT IF EXISTS FK_CAT_SENSIBILIDAD_DOMINIO;
	--ALTER TABLE CALIDAD.DQ_DOMINIO DROP CONSTRAINT IF EXISTS FK_CAT_ESTCONCEPTUALIZACION_DOMINIO;
	SELECT 1;
END;


IF OBJECT_ID(N'CALIDAD.DQ_ATRIBUTO', N'U') IS NOT NULL
BEGIN
	ALTER TABLE CALIDAD.DQ_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_DOMINIO_ATRIBUTO;
	--ALTER TABLE CALIDAD.DQ_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_CAT_SENSIBILIDAD_ATRIBUTO;
	--ALTER TABLE CALIDAD.DQ_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_CAT_ESTCONCEPTUALIZACION_ATRIBUTO;
END;


IF OBJECT_ID(N'CALIDAD.DQ_REGLA_ATRIBUTO', N'U') IS NOT NULL
BEGIN
	ALTER TABLE CALIDAD.DQ_REGLA_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_DOMINIO_REGLAATRIBUTO;
	ALTER TABLE CALIDAD.DQ_REGLA_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_ATRIBUTO_REGLAATRIBUTO;
	ALTER TABLE CALIDAD.DQ_REGLA_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_CAT_DIMCALIDAD_REGLAATRIBUTO;
	ALTER TABLE CALIDAD.DQ_REGLA_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_CAT_ESTCONCEPTUALIZACION_REGLAATRIBUTO;
END;


IF OBJECT_ID(N'CALIDAD.DQ_REGLA_ATRIBUTO', N'U') IS NOT NULL
BEGIN
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA DROP CONSTRAINT IF EXISTS FK_EJECUCION_RESREGLA;
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA DROP CONSTRAINT IF EXISTS FK_DOMINIO_RESREGLA;
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA DROP CONSTRAINT IF EXISTS FK_ATRIBUTO_RESREGLA;
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA DROP CONSTRAINT IF EXISTS FK_CAT_DIMCALIDAD_RESREGLA;
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA DROP CONSTRAINT IF EXISTS FK_CAT_REGLAATRIBUTO_RESREGLA;
END;


IF OBJECT_ID(N'CALIDAD.DQ_RESULTADO_REGLA_DETALLE', N'U') IS NOT NULL
BEGIN
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE DROP CONSTRAINT IF EXISTS FK_EJECUCION_RESREGLADET;
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE DROP CONSTRAINT IF EXISTS FK_DOMINIO_RESREGLADET;
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE DROP CONSTRAINT IF EXISTS FK_ATRIBUTO_RESREGLADET;
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE DROP CONSTRAINT IF EXISTS FK_CAT_DIMCALIDAD_RESREGLADET;
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE DROP CONSTRAINT IF EXISTS FK_CAT_REGLAATRIBUTO_RESREGLADET;
END;


IF OBJECT_ID(N'CALIDAD.DQ_RESULTADO_DOMINIO', N'U') IS NOT NULL
BEGIN
	ALTER TABLE CALIDAD.DQ_RESULTADO_DOMINIO DROP CONSTRAINT IF EXISTS FK_EJECUCION_RESDOMINIO;
	ALTER TABLE CALIDAD.DQ_RESULTADO_DOMINIO DROP CONSTRAINT IF EXISTS FK_DOMINIO_RESDOMINIO;
	ALTER TABLE CALIDAD.DQ_RESULTADO_DOMINIO DROP CONSTRAINT IF EXISTS FK_CAT_DIMCALIDAD_RESDOMINIO;
END;


IF OBJECT_ID(N'CALIDAD.DQ_RESULTADO_ATRIBUTO', N'U') IS NOT NULL
BEGIN
	ALTER TABLE CALIDAD.DQ_RESULTADO_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_EJECUCION_RESATRIBUTO;
	ALTER TABLE CALIDAD.DQ_RESULTADO_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_DOMINIO_RESATRIBUTO;
	ALTER TABLE CALIDAD.DQ_RESULTADO_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_ATRIBUTO_RESATRIBUTO;
	ALTER TABLE CALIDAD.DQ_RESULTADO_ATRIBUTO DROP CONSTRAINT IF EXISTS FK_CAT_DIMCALIDAD_RESATRIBUTO;
END;


IF OBJECT_ID(N'CALIDAD.DQ_RESULTADO_REGISTRO', N'U') IS NOT NULL
BEGIN
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGISTRO DROP CONSTRAINT IF EXISTS FK_EJECUCION_RESREGISTRO;
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGISTRO DROP CONSTRAINT IF EXISTS FK_DOMINIO_RESREGISTRO;
	ALTER TABLE CALIDAD.DQ_RESULTADO_REGISTRO DROP CONSTRAINT IF EXISTS FK_CAT_DIMCALIDAD_RESREGISTRO;
END;


IF OBJECT_ID(N'CALIDAD.DQ_EJECUCION_DOMINIO', N'U') IS NOT NULL
BEGIN
	ALTER TABLE CALIDAD.DQ_EJECUCION_DOMINIO DROP CONSTRAINT IF EXISTS FK_EJECUCION_EJECDOMINIO;
	ALTER TABLE CALIDAD.DQ_EJECUCION_DOMINIO DROP CONSTRAINT IF EXISTS FK_DOMINIO_EJECDOMINIO;
END;
/**************************************************/


/**************************************************/
IF OBJECT_ID(N'CALIDAD.DQ_DOMINIO', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.DQ_DOMINIO;
END;
CREATE TABLE CALIDAD.DQ_DOMINIO (
	DOMINIO_ID	INTEGER IDENTITY(1,1) PRIMARY KEY
	,NOMBRE VARCHAR(50)
	,TIPO_DOMINIO_ID INT
	,DESCRIPCION VARCHAR(500)
	,CONCEPTO_CLAVE_NEGOCIO VARCHAR(100)
	,PROCESO_CLAVE_ASOCIADO VARCHAR(100)
	--,SENSIBILIDAD_ID INT
	,SENSIBILIDAD VARCHAR(20)
	,KDE_NUM INT
	,MCA_REGLAS_CALIDAD BIT
	--,ESTADO_CONCEPTUALIZACION_ID INT
	,ESTADO_CONCEPTUALIZACION VARCHAR(20)
	,PRIORIDAD INT
	,OLA_IMPLEMENTACION INT
	,VIGENCIA_INICIO DATE
	,VIGENCIA_FIN DATE
	,VERSION VARCHAR(20)
	,FECHA_REGISTRO DATETIME
	,FECHA_ACTUALIZACION DATETIME
	,USUARIO_REGISTRO VARCHAR(25)
	,USUARIO_ACTUALIZACION VARCHAR(25)
);


IF OBJECT_ID(N'CALIDAD.DQ_ATRIBUTO', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.DQ_ATRIBUTO;
END;
CREATE TABLE CALIDAD.DQ_ATRIBUTO (
	ATRIBUTO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	,DOMINIO_ID INT
	,NOMBRE_TECNICO VARCHAR(100)
	,DESCRIPCION_FUNCIONAL VARCHAR(500)
	,CONCEPTO_NEGOCIO VARCHAR(100)
	,TIPO_DATO VARCHAR(20)
	,FORMATO VARCHAR(200)
	,LONGITUD INT
	,PRECISION INT
	,ESCALA INT
	,UNIDAD_MEDIDA VARCHAR(25)
	,VALOR_DEFECTO VARCHAR(25)
	,MCA_OBLIGATORIO BIT
	,MCA_IDENTIFICADOR BIT
	,MCA_LLAVE_NEGOCIO BIT
	,MCA_KDE BIT
	,PESO_ATRIBUTO FLOAT
	,CATALOGO_VALORES VARCHAR(500)
	--,SENSIBILIDAD_ID INT
	,SENSIBILIDAD VARCHAR(20)
	--,ESTADO_CONCEPTUALIZACION_ID INT
	,ESTADO_CONCEPTUALIZACION VARCHAR(20)
	,VIGENCIA_INICIO DATE
	,VIGENCIA_FIN DATE
	,VERSION VARCHAR(20)
	,FECHA_ULTIMO_CONTROL DATETIME
	,OBSERVACIONES VARCHAR(500)
	,FECHA_REGISTRO DATETIME
	,FECHA_ACTUALIZACION DATETIME
	,USUARIO_REGISTRO VARCHAR(25)
	,USUARIO_ACTUALIZACION VARCHAR(25)
);


IF OBJECT_ID(N'CALIDAD.DQ_REGLA_ATRIBUTO', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.DQ_REGLA_ATRIBUTO;
END;
CREATE TABLE CALIDAD.DQ_REGLA_ATRIBUTO (
	REGLA_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	,DOMINIO_ID INT
	,ATRIBUTO_ID INT
	,DIMENSION_CALIDAD_ID INT
	,DESCRIPCION_REGLA VARCHAR(500)
	,EXPRESION_REGULAR VARCHAR(500)
	,UMBRAL_MINIMO FLOAT
	,MARGEN_TOLERANCIA FLOAT
	,ES_CRITICA_GATING BIT
	,PESO_REGLA FLOAT
	,RESPONSABLE VARCHAR(100)
	,ESTADO VARCHAR(15)
	,VIGENCIA_INICIO DATE
	,VIGENCIA_FIN DATE
	,VERSION VARCHAR(20)
	,OBSERVACIONES VARCHAR(500)
	,FECHA_REGISTRO DATETIME
	,FECHA_ACTUALIZACION DATETIME
	,USUARIO_REGISTRO VARCHAR(25)
	,USUARIO_ACTUALIZACION VARCHAR(25)
);


IF OBJECT_ID(N'CALIDAD.CAT_DIMENSION_CALIDAD', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.CAT_DIMENSION_CALIDAD;
END;
CREATE TABLE CALIDAD.CAT_DIMENSION_CALIDAD (
	DIMENSION_CALIDAD_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	,NOMBRE VARCHAR(100)
	,DEFINICION VARCHAR(500)
	,ESTADO VARCHAR(15)
);


IF OBJECT_ID(N'CALIDAD.DQ_RESULTADO_REGLA_DETALLE', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE;
END;
CREATE TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE (
	DETALLE_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	,EJECUCION_ID INT
	,DOMINIO_ID INT
	,ATRIBUTO_ID INT
	,REGLA_ID INT
	,DIMENSION_CALIDAD_ID INT
	,ID_REGISTRO_FUENTE VARCHAR(100)
	,VALOR_OBSERVADO VARCHAR(4000)
	,ESTADO_VALIDACION VARCHAR(15)
	,CODIGO_ERROR VARCHAR(4000)
	,DESCRIPCION_ERROR VARCHAR(500)
	,FECHA_EVENTO DATETIME
);


IF OBJECT_ID(N'CALIDAD.DQ_RESULTADO_REGLA', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.DQ_RESULTADO_REGLA;
END;
CREATE TABLE CALIDAD.DQ_RESULTADO_REGLA (
	RESULTADO_REGLA_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	,EJECUCION_ID INT
	,DOMINIO_ID INT
	,ATRIBUTO_ID INT
	,REGLA_ID INT
	,DIMENSION_CALIDAD_ID INT
	,REGISTROS_EVALUADOS BIGINT
	,REGISTROS_CUMPLE BIGINT
	,REGISTROS_CUMPLE_PARCIAL BIGINT
	,REGISTROS_NO_CUMPLE BIGINT
	,TASA_CUMPLIMIENTO FLOAT
	,TASA_ERROR FLOAT
	,UMBRAL_MINIMO FLOAT
	,MARGEN_TOLERANCIA FLOAT
	,MCA_UMBRAL_CUMPLIDO BIT
	,PESO_REGLA FLOAT
	,SCORE_REGLA FLOAT
	,FECHA_CALCULO DATETIME
);


IF OBJECT_ID(N'CALIDAD.DQ_RESULTADO_ATRIBUTO', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.DQ_RESULTADO_ATRIBUTO;
END;
CREATE TABLE CALIDAD.DQ_RESULTADO_ATRIBUTO (
	RESULTADO_ATRIBUTO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	,EJECUCION_ID INT
	,DOMINIO_ID INT
	,ATRIBUTO_ID INT
	,DIMENSION_CALIDAD_ID INT
	,VERSION_ATRIBUTO VARCHAR(20)
	,REGISTROS_EVALUADOS BIGINT
	,REGISTROS_VALIDOS BIGINT
	,REGISTROS_INVALIDOS BIGINT
	,SCORE_DIMENSION_ATRIBUTO FLOAT
	,PESO_ATRIBUTO FLOAT
	,SCORE_ATRIBUTO_PONDERADO FLOAT
	,FECHA_CALCULO DATETIME
);


IF OBJECT_ID(N'CALIDAD.DQ_RESULTADO_DOMINIO', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.DQ_RESULTADO_DOMINIO;
END;
CREATE TABLE CALIDAD.DQ_RESULTADO_DOMINIO (
	RESULTADO_DOMINIO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	,EJECUCION_ID INT
	,DOMINIO_ID INT
	,DIMENSION_CALIDAD_ID INT
	,VERSION_DOMINIO VARCHAR(20)
	,REGISTROS_EVALUADOS BIGINT
	,REGISTROS_VALIDOS BIGINT
	,REGISTROS_INVALIDOS BIGINT
	,SCORE_DIMENSION_DOMINIO FLOAT
	,SCORE_DOMINIO_TOTAL FLOAT
	,FECHA_CALCULO DATETIME
);


IF OBJECT_ID(N'CALIDAD.DQ_RESULTADO_REGISTRO', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.DQ_RESULTADO_REGISTRO;
END;
CREATE TABLE CALIDAD.DQ_RESULTADO_REGISTRO (
	RESULTADO_REGISTRO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	,EJECUCION_ID INT
	,DOMINIO_ID INT
	,DIMENSION_CALIDAD_ID INT
	,SCORE_DIMENSION_REGISTRO FLOAT
	,FECHA_CALCULO DATETIME
);


IF OBJECT_ID(N'CALIDAD.DQ_EJECUCION', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.DQ_EJECUCION;
END;
CREATE TABLE CALIDAD.DQ_EJECUCION (
	EJECUCION_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	,TIPO_FLUJO VARCHAR(100)
	,FECHA_INICIO DATETIME
	,FECHA_FIN DATETIME
	,VENTANA_INICIO DATETIME
	,VENTANA_FIN DATETIME
	,ESTADO VARCHAR(15)
	,ORIGEN_DISPARO VARCHAR(100)
	,VERSION_CONFIGURACION VARCHAR
	,OBSERVACIONES VARCHAR(4000)
	,FECHA_REGISTRO DATETIME
	,USUARIO_REGISTRO VARCHAR(25)
);


IF OBJECT_ID(N'CALIDAD.DQ_EJECUCION_DOMINIO', N'U') IS NOT NULL
BEGIN
	DROP TABLE CALIDAD.DQ_EJECUCION_DOMINIO;
END;
CREATE TABLE CALIDAD.DQ_EJECUCION_DOMINIO (
	EJECUCION_ID INT
	,DOMINIO_ID INT
	,VERSION_DOMINIO VARCHAR(20)
	,REGISTROS_EVALUADOS BIGINT
	,REGISTROS_VALIDOS BIGINT
	,REGISTROS_INVALIDOS BIGINT
	,SCORE_DOMINIO FLOAT
	,ESTADO VARCHAR(15)
);
/**************************************************/


/**************************************************/
/*
ALTER TABLE CALIDAD.DQ_DOMINIO
	ADD CONSTRAINT FK_CAT_SENSIBILIDAD_DOMINIO FOREIGN KEY (SENSIBILIDAD_ID) 
	REFERENCES CALIDAD.CAT_SENSIBILIDAD_ID(SENSIBILIDAD_ID);
*/
/*
ALTER TABLE CALIDAD.DQ_DOMINIO
	ADD CONSTRAINT FK_CAT_ESTCONCEPTUALIZACION_DOMINIO FOREIGN KEY (ESTADO_CONCEPTUALIZACION_ID) 
	REFERENCES CALIDAD.CAT_ESTADO_CONCEPTUALIZACION(ESTADO_CONCEPTUALIZACION_ID);
*/


ALTER TABLE CALIDAD.DQ_ATRIBUTO
	ADD CONSTRAINT FK_DOMINIO_ATRIBUTO FOREIGN KEY (DOMINIO_ID) 
	REFERENCES CALIDAD.DQ_DOMINIO(DOMINIO_ID);
/*
ALTER TABLE CALIDAD.DQ_ATRIBUTO
	ADD CONSTRAINT FK_CAT_SENSIBILIDAD_ATRIBUTO FOREIGN KEY (SENSIBILIDAD_ID) 
	REFERENCES CALIDAD.CAT_SENSIBILIDAD_ID(SENSIBILIDAD_ID);
*/
/*
ALTER TABLE CALIDAD.DQ_ATRIBUTO
	ADD CONSTRAINT FK_CAT_ESTCONCEPTUALIZACION_ATRIBUTO FOREIGN KEY (ESTADO_CONCEPTUALIZACION_ID) 
	REFERENCES CALIDAD.CAT_ESTADO_CONCEPTUALIZACION(ESTADO_CONCEPTUALIZACION_ID);
*/


ALTER TABLE CALIDAD.DQ_REGLA_ATRIBUTO
	ADD CONSTRAINT FK_DOMINIO_REGLAATRIBUTO FOREIGN KEY (DOMINIO_ID) 
	REFERENCES CALIDAD.DQ_DOMINIO(DOMINIO_ID);
ALTER TABLE CALIDAD.DQ_REGLA_ATRIBUTO
	ADD CONSTRAINT FK_ATRIBUTO_REGLAATRIBUTO FOREIGN KEY (ATRIBUTO_ID) 
	REFERENCES CALIDAD.DQ_ATRIBUTO(ATRIBUTO_ID);
ALTER TABLE CALIDAD.DQ_REGLA_ATRIBUTO
	ADD CONSTRAINT FK_CAT_DIMCALIDAD_REGLAATRIBUTO FOREIGN KEY (DIMENSION_CALIDAD_ID) 
	REFERENCES CALIDAD.CAT_DIMENSION_CALIDAD(DIMENSION_CALIDAD_ID);
/*
ALTER TABLE CALIDAD.DQ_REGLA_ATRIBUTO
	ADD CONSTRAINT FK_CAT_ESTCONCEPTUALIZACION_REGLAATRIBUTO FOREIGN KEY (ESTADO_CONCEPTUALIZACION_ID) 
	REFERENCES CALIDAD.CAT_ESTADO_CONCEPTUALIZACION(ESTADO_CONCEPTUALIZACION_ID);
*/


ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA
	ADD CONSTRAINT FK_EJECUCION_RESREGLA FOREIGN KEY (EJECUCION_ID) 
	REFERENCES CALIDAD.DQ_EJECUCION(EJECUCION_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA
	ADD CONSTRAINT FK_DOMINIO_RESREGLA FOREIGN KEY (DOMINIO_ID) 
	REFERENCES CALIDAD.DQ_DOMINIO(DOMINIO_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA
	ADD CONSTRAINT FK_ATRIBUTO_RESREGLA FOREIGN KEY (ATRIBUTO_ID) 
	REFERENCES CALIDAD.DQ_ATRIBUTO(ATRIBUTO_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA
	ADD CONSTRAINT FK_CAT_DIMCALIDAD_RESREGLA FOREIGN KEY (DIMENSION_CALIDAD_ID) 
	REFERENCES CALIDAD.CAT_DIMENSION_CALIDAD(DIMENSION_CALIDAD_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA
	ADD CONSTRAINT FK_CAT_REGLAATRIBUTO_RESREGLA FOREIGN KEY (REGLA_ID) 
	REFERENCES CALIDAD.DQ_REGLA_ATRIBUTO(REGLA_ID);
	

ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE
	ADD CONSTRAINT FK_EJECUCION_RESREGLADET FOREIGN KEY (EJECUCION_ID) 
	REFERENCES CALIDAD.DQ_EJECUCION(EJECUCION_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE
	ADD CONSTRAINT FK_DOMINIO_RESREGLADET FOREIGN KEY (DOMINIO_ID) 
	REFERENCES CALIDAD.DQ_DOMINIO(DOMINIO_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE
	ADD CONSTRAINT FK_ATRIBUTO_RESREGLADET FOREIGN KEY (ATRIBUTO_ID) 
	REFERENCES CALIDAD.DQ_ATRIBUTO(ATRIBUTO_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE
	ADD CONSTRAINT FK_CAT_DIMCALIDAD_RESREGLADET FOREIGN KEY (DIMENSION_CALIDAD_ID) 
	REFERENCES CALIDAD.CAT_DIMENSION_CALIDAD(DIMENSION_CALIDAD_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_REGLA_DETALLE
	ADD CONSTRAINT FK_CAT_REGLAATRIBUTO_RESREGLADET FOREIGN KEY (REGLA_ID) 
	REFERENCES CALIDAD.DQ_REGLA_ATRIBUTO(REGLA_ID);
	
	
ALTER TABLE CALIDAD.DQ_RESULTADO_DOMINIO
	ADD CONSTRAINT FK_EJECUCION_RESDOMINIO FOREIGN KEY (EJECUCION_ID) 
	REFERENCES CALIDAD.DQ_EJECUCION(EJECUCION_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_DOMINIO
	ADD CONSTRAINT FK_DOMINIO_RESDOMINIO FOREIGN KEY (DOMINIO_ID) 
	REFERENCES CALIDAD.DQ_DOMINIO(DOMINIO_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_DOMINIO
	ADD CONSTRAINT FK_CAT_DIMCALIDAD_RESDOMINIO FOREIGN KEY (DIMENSION_CALIDAD_ID) 
	REFERENCES CALIDAD.CAT_DIMENSION_CALIDAD(DIMENSION_CALIDAD_ID);


ALTER TABLE CALIDAD.DQ_RESULTADO_ATRIBUTO
	ADD CONSTRAINT FK_EJECUCION_RESATRIBUTO FOREIGN KEY (EJECUCION_ID) 
	REFERENCES CALIDAD.DQ_EJECUCION(EJECUCION_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_ATRIBUTO
	ADD CONSTRAINT FK_DOMINIO_RESATRIBUTO FOREIGN KEY (DOMINIO_ID) 
	REFERENCES CALIDAD.DQ_DOMINIO(DOMINIO_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_ATRIBUTO
	ADD CONSTRAINT FK_ATRIBUTO_RESATRIBUTO FOREIGN KEY (ATRIBUTO_ID) 
	REFERENCES CALIDAD.DQ_ATRIBUTO(ATRIBUTO_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_ATRIBUTO
	ADD CONSTRAINT FK_CAT_DIMCALIDAD_RESATRIBUTO FOREIGN KEY (DIMENSION_CALIDAD_ID) 
	REFERENCES CALIDAD.CAT_DIMENSION_CALIDAD(DIMENSION_CALIDAD_ID);

	
ALTER TABLE CALIDAD.DQ_RESULTADO_REGISTRO
	ADD CONSTRAINT FK_EJECUCION_RESREGISTRO FOREIGN KEY (EJECUCION_ID) 
	REFERENCES CALIDAD.DQ_EJECUCION(EJECUCION_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_REGISTRO
	ADD CONSTRAINT FK_DOMINIO_RESREGISTRO FOREIGN KEY (DOMINIO_ID) 
	REFERENCES CALIDAD.DQ_DOMINIO(DOMINIO_ID);
ALTER TABLE CALIDAD.DQ_RESULTADO_REGISTRO
	ADD CONSTRAINT FK_CAT_DIMCALIDAD_RESREGISTRO FOREIGN KEY (DIMENSION_CALIDAD_ID) 
	REFERENCES CALIDAD.CAT_DIMENSION_CALIDAD(DIMENSION_CALIDAD_ID);


ALTER TABLE CALIDAD.DQ_EJECUCION_DOMINIO
	ADD CONSTRAINT FK_EJECUCION_EJECDOMINIO FOREIGN KEY (EJECUCION_ID) 
	REFERENCES CALIDAD.DQ_EJECUCION(EJECUCION_ID);
ALTER TABLE CALIDAD.DQ_EJECUCION_DOMINIO
	ADD CONSTRAINT FK_DOMINIO_EJECDOMINIO FOREIGN KEY (DOMINIO_ID) 
	REFERENCES CALIDAD.DQ_DOMINIO(DOMINIO_ID);
/**************************************************/


/**************************************************/
DELETE FROM CALIDAD.DQ_RESULTADO_REGISTRO;
DBCC CHECKIDENT ('CALIDAD.DQ_RESULTADO_REGISTRO', RESEED, 1);
DELETE FROM CALIDAD.DQ_EJECUCION;
DBCC CHECKIDENT ('CALIDAD.DQ_EJECUCION', RESEED, 1);
DELETE FROM CALIDAD.DQ_RESULTADO_REGLA_DETALLE;
DBCC CHECKIDENT ('CALIDAD.DQ_RESULTADO_REGLA_DETALLE', RESEED, 1);
DELETE FROM CALIDAD.DQ_RESULTADO_DOMINIO;
DBCC CHECKIDENT ('CALIDAD.DQ_RESULTADO_DOMINIO', RESEED, 1);
DELETE FROM CALIDAD.DQ_RESULTADO_ATRIBUTO;
DBCC CHECKIDENT ('CALIDAD.DQ_RESULTADO_ATRIBUTO', RESEED, 1);
DELETE FROM CALIDAD.DQ_REGLA_ATRIBUTO;
DBCC CHECKIDENT ('CALIDAD.DQ_REGLA_ATRIBUTO', RESEED, 1);
DELETE FROM CALIDAD.DQ_ATRIBUTO;
DBCC CHECKIDENT ('CALIDAD.DQ_ATRIBUTO', RESEED, 1);
DELETE FROM CALIDAD.DQ_DOMINIO;
DBCC CHECKIDENT ('CALIDAD.DQ_DOMINIO', RESEED, 1);
DELETE FROM CALIDAD.CAT_DIMENSION_CALIDAD;
DBCC CHECKIDENT ('CALIDAD.CAT_DIMENSION_CALIDAD', RESEED, 1);
/**************************************************/


/**************************************************/
INSERT INTO CALIDAD.DQ_DOMINIO VALUES ( 
	--NULL --DOMINIO_ID
	'Entidad Pública' --NOMBRE
	,NULL --TIPO_DOMINIO_ID
	,'Entidades públicas de Colombia' --DESCRIPCION
	,NULL --CONCEPTO_CLAVE_NEGOCIO
	,NULL --PROCESO_CLAVE_ASOCIADO
	,'Pública' --SENSIBILIDAD
	,NULL --KDE_NUM
	,1 --MCA_REGLAS_CALIDAD
	,'Conceptualizado' --ESTADO_CONCEPTUALIZACION
	,1 --PRIORIDAD
	,1 --OLA_IMPLEMENTACION
	,'2025-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

SELECT * FROM CALIDAD.DQ_DOMINIO;


INSERT INTO CALIDAD.DQ_ATRIBUTO VALUES (
	--NULL --ATRIBUTO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	1 --DOMINIO_ID
	,'EMAIL' --NOMBRE_TECNICO
	,'Correo electrónico de contacto con la Entidad Pública' --DESCRIPCION_FUNCIONAL
	,NULL --CONCEPTO_NEGOCIO
	,'VARCHAR' --TIPO_DATO
	,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$' --FORMATO
	,500 --LONGITUD
	,NULL --PRECISION
	,NULL --ESCALA
	,NULL --UNIDAD_MEDIDA
	,NULL --VALOR_DEFECTO
	,0 --MCA_OBLIGATORIO
	,0 --MCA_IDENTIFICADOR
	,0 --MCA_LLAVE_NEGOCIO
	,1 --MCA_KDE
	,1./6. --PESO_ATRIBUTO
	,NULL --CATALOGO_VALORES
	,'Pública' --SENSIBILIDAD
	,'Conceptualizado' --ESTADO_CONCEPTUALIZACION
	,'2015-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --FECHA_ULTIMO_CONTROL
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

SELECT * FROM CALIDAD.DQ_ATRIBUTO;


INSERT INTO CALIDAD.DQ_ATRIBUTO VALUES (
	--NULL --ATRIBUTO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	1 --DOMINIO_ID
	,'NOMBRE' --NOMBRE_TECNICO
	,'Nombre de la Entidad Pública' --DESCRIPCION_FUNCIONAL
	,NULL --CONCEPTO_NEGOCIO
	,'VARCHAR' --TIPO_DATO
	,'^[^a-z]+$' --FORMATO
	,500 --LONGITUD
	,NULL --PRECISION
	,NULL --ESCALA
	,NULL --UNIDAD_MEDIDA
	,NULL --VALOR_DEFECTO
	,1	--MCA_OBLIGATORIO
	,0 --MCA_IDENTIFICADOR
	,0 --MCA_LLAVE_NEGOCIO
	,1 --MCA_KDE
	,1./6. --PESO_ATRIBUTO
	,NULL --CATALOGO_VALORES
	,'Pública' --SENSIBILIDAD
	,'Conceptualizado' --ESTADO_CONCEPTUALIZACION
	,'2015-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --FECHA_ULTIMO_CONTROL
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_ATRIBUTO VALUES (
	--NULL --ATRIBUTO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	1 --DOMINIO_ID
	,'CCB_TELEFONO' --NOMBRE_TECNICO
	,'Teléfono de la Entidad Pública' --DESCRIPCION_FUNCIONAL
	,NULL --CONCEPTO_NEGOCIO
	,'VARCHAR' --TIPO_DATO
	,'^(\+)?(\(?\d+\)?)(([\s-]+)?(\d+)){0,}$' --FORMATO
	,500 --LONGITUD
	,NULL --PRECISION
	,NULL --ESCALA
	,NULL --UNIDAD_MEDIDA
	,NULL --VALOR_DEFECTO
	,0	--MCA_OBLIGATORIO
	,0 --MCA_IDENTIFICADOR
	,0 --MCA_LLAVE_NEGOCIO
	,1 --MCA_KDE
	,1./6. --PESO_ATRIBUTO
	,NULL --CATALOGO_VALORES
	,'Pública' --SENSIBILIDAD
	,'Conceptualizado' --ESTADO_CONCEPTUALIZACION
	,'2015-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --FECHA_ULTIMO_CONTROL
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_ATRIBUTO VALUES (
	--NULL --ATRIBUTO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	1 --DOMINIO_ID
	,'CCB_PAGINA_WEB' --NOMBRE_TECNICO
	,'Página web de la Entidad Pública' --DESCRIPCION_FUNCIONAL
	,NULL --CONCEPTO_NEGOCIO
	,'VARCHAR' --TIPO_DATO
	,'^(http|HTTP|https|HTTPS)?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&\/=]*)$' --FORMATO
	,500 --LONGITUD
	,NULL --PRECISION
	,NULL --ESCALA
	,NULL --UNIDAD_MEDIDA
	,NULL --VALOR_DEFECTO
	,0	--MCA_OBLIGATORIO
	,0 --MCA_IDENTIFICADOR
	,0 --MCA_LLAVE_NEGOCIO
	,1 --MCA_KDE
	,1./6. --PESO_ATRIBUTO
	,NULL --CATALOGO_VALORES
	,'Pública' --SENSIBILIDAD
	,'Conceptualizado' --ESTADO_CONCEPTUALIZACION
	,'2015-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --FECHA_ULTIMO_CONTROL
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_ATRIBUTO VALUES (
	--NULL --ATRIBUTO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	1 --DOMINIO_ID
	,'LATITUD' --NOMBRE_TECNICO
	,'Latitud de la Entidad Pública' --DESCRIPCION_FUNCIONAL
	,NULL --CONCEPTO_NEGOCIO
	,'NUMERIC' --TIPO_DATO
	,'^(-?[1-8]?\d(?:\.\d{1,18})?|90(?:\.0{1,18})?)$' --FORMATO
	,NULL --LONGITUD
	,10 --PRECISION
	,7 --ESCALA
	,NULL --UNIDAD_MEDIDA
	,NULL --VALOR_DEFECTO
	,0	--MCA_OBLIGATORIO
	,0 --MCA_IDENTIFICADOR
	,0 --MCA_LLAVE_NEGOCIO
	,1 --MCA_KDE
	,1./6. --PESO_ATRIBUTO
	,NULL --CATALOGO_VALORES
	,'Pública' --SENSIBILIDAD
	,'Conceptualizado' --ESTADO_CONCEPTUALIZACION
	,'2015-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --FECHA_ULTIMO_CONTROL
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_ATRIBUTO VALUES (
	--NULL --ATRIBUTO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	1 --DOMINIO_ID
	,'LONGITUD' --NOMBRE_TECNICO
	,'Longitud de la Entidad Pública' --DESCRIPCION_FUNCIONAL
	,NULL --CONCEPTO_NEGOCIO
	,'NUMERIC' --TIPO_DATO
	,'^(-?(?:1[0-7]|[1-9])?\d(?:\.\d{1,18})?|180(?:\.0{1,18})?)$' --FORMATO
	,NULL --LONGITUD
	,10 --PRECISION
	,7 --ESCALA
	,NULL --UNIDAD_MEDIDA
	,NULL --VALOR_DEFECTO
	,0	--MCA_OBLIGATORIO
	,0 --MCA_IDENTIFICADOR
	,0 --MCA_LLAVE_NEGOCIO
	,1 --MCA_KDE
	,1./6. --PESO_ATRIBUTO
	,NULL --CATALOGO_VALORES
	,'Pública' --SENSIBILIDAD
	,'Conceptualizado' --ESTADO_CONCEPTUALIZACION
	,'2015-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --FECHA_ULTIMO_CONTROL
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_ATRIBUTO VALUES (
	--NULL --ATRIBUTO_ID INTEGER IDENTITY(1,1) PRIMARY KEY
	1 --DOMINIO_ID
	,'DM_INSTITUCION_COD_INSTITUCION' --NOMBRE_TECNICO
	,'Código único de identificación de la Entidad Pública' --DESCRIPCION_FUNCIONAL
	,NULL --CONCEPTO_NEGOCIO
	,'VARCHAR' --TIPO_DATO
	,NULL --FORMATO
	,500 --LONGITUD
	,NULL --PRECISION
	,NULL --ESCALA
	,NULL --UNIDAD_MEDIDA
	,NULL --VALOR_DEFECTO
	,1	--MCA_OBLIGATORIO
	,1 --MCA_IDENTIFICADOR
	,1 --MCA_LLAVE_NEGOCIO
	,1 --MCA_KDE
	,1./6. --PESO_ATRIBUTO
	,NULL --CATALOGO_VALORES
	,'Pública' --SENSIBILIDAD
	,'Conceptualizado' --ESTADO_CONCEPTUALIZACION
	,'2015-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --FECHA_ULTIMO_CONTROL
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

SELECT * FROM CALIDAD.DQ_ATRIBUTO;


INSERT INTO CALIDAD.CAT_DIMENSION_CALIDAD VALUES (
	--NULL -- DIMENSION_CALIDAD_ID
	'Validez' --NOMBRE
	,'Grado en que los datos se ajustan en contenido a un valor aceptable en el dominio de la variable o que satisfacen el formato establecido.' --DEFINICION
	,'activo' --ESTADO
);

INSERT INTO CALIDAD.CAT_DIMENSION_CALIDAD VALUES (
	--NULL -- DIMENSION_CALIDAD_ID
	'Completitud' --NOMBRE
	,'Grado en que se permite que los datos sean poblados o no con un valor.' --DEFINICION
	,'activo' --ESTADO
);

INSERT INTO CALIDAD.CAT_DIMENSION_CALIDAD VALUES (
	--NULL -- DIMENSION_CALIDAD_ID
	'Unicidad' --NOMBRE
	,'Grado en el que los datos pueden estar repetidos o no dentro del mismo sistema.' --DEFINICION
	,'activo' --ESTADO
);

INSERT INTO CALIDAD.CAT_DIMENSION_CALIDAD VALUES (
	--NULL -- DIMENSION_CALIDAD_ID
	'Oportunidad' --NOMBRE
	,'Grado en el que los datos están actualizados y son consistentes con el evento de negocio más reciente.' --DEFINICION
	,'activo' --ESTADO
);

INSERT INTO CALIDAD.CAT_DIMENSION_CALIDAD VALUES (
	--NULL -- DIMENSION_CALIDAD_ID
	'Precisión' --NOMBRE
	,'Grado en que los datos son consistentes con la realidad o con una fuente autorizada de confianza o de referencia.' --DEFINICION
	,'activo' --ESTADO
);

INSERT INTO CALIDAD.CAT_DIMENSION_CALIDAD VALUES (
	--NULL -- DIMENSION_CALIDAD_ID
	'Lógica' --NOMBRE
	,'Grado en que los datos se ajustan a las pruebas de razonabilidad del negocio, basadas en escenarios del mundo real y valores de otros datos.' --DEFINICION
	,'activo' --ESTADO
);

INSERT INTO CALIDAD.CAT_DIMENSION_CALIDAD VALUES (
	--NULL -- DIMENSION_CALIDAD_ID
	'Cobertura' --NOMBRE
	,'Grado en que los datos están incluidos en todas las aplicaciones y sistemas de soporte al negocio que los requieren.' --DEFINICION
	,'activo' --ESTADO
);

INSERT INTO CALIDAD.CAT_DIMENSION_CALIDAD VALUES (
	--NULL -- DIMENSION_CALIDAD_ID
	'Integridad' --NOMBRE
	,'Grado en que los datos conservan un contenido consistente a través de los diferentes almacenes de datos.' --DEFINICION
	,'activo' --ESTADO
);

SELECT * FROM CALIDAD.CAT_DIMENSION_CALIDAD;


INSERT INTO CALIDAD.DQ_REGLA_ATRIBUTO VALUES (
	--NULL --REGLA_ID
	1 --DOMINIO_ID
	,1 --ATRIBUTO_ID
	,1 --DIMENSION_CALIDAD_ID
	,'El correo electrónico debe tener un formato válido' --DESCRIPCION_REGLA
	,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$' --EXPRESION_REGULAR
	,0.8 --UMBRAL_MINIMO
	,0.05 --MARGEN_TOLERANCIA
	,0 --ES_CRITICA_GATING
	,0.5 --PESO_REGLA
	,CURRENT_USER --RESPONSABLE
	,'activo' -- ESTADO
	,'2025-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_REGLA_ATRIBUTO VALUES (
	--NULL --REGLA_ID
	1 --DOMINIO_ID
	,1 --ATRIBUTO_ID
	,2 --DIMENSION_CALIDAD_ID
	,'El correo electrónico no puede estar vacío' --DESCRIPCION_REGLA
	,'.+' --EXPRESION_REGULAR
	,0.8 --UMBRAL_MINIMO
	,0.05 --MARGEN_TOLERANCIA
	,0 --ES_CRITICA_GATING
	,0.5 --PESO_REGLA
	,CURRENT_USER --RESPONSABLE
	,'activo' -- ESTADO
	,'2025-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_REGLA_ATRIBUTO VALUES (
	--NULL --REGLA_ID
	1 --DOMINIO_ID
	,2 --ATRIBUTO_ID
	,1 --DIMENSION_CALIDAD_ID
	,'El nombre de la entidad debe estar en mayúsculas sostenidas' --DESCRIPCION_REGLA
	,'^[^a-z]+$' --EXPRESION_REGULAR
	,0.8 --UMBRAL_MINIMO
	,0.05 --MARGEN_TOLERANCIA
	,0 --ES_CRITICA_GATING
	,0.5 --PESO_REGLA
	,CURRENT_USER --RESPONSABLE
	,'activo' -- ESTADO
	,'2025-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_REGLA_ATRIBUTO VALUES (
	--NULL --REGLA_ID
	1 --DOMINIO_ID
	,2 --ATRIBUTO_ID
	,2 --DIMENSION_CALIDAD_ID
	,'El nombre de la entidad no puede estar vacío' --DESCRIPCION_REGLA
	,'.+' --EXPRESION_REGULAR
	,0.8 --UMBRAL_MINIMO
	,0.05 --MARGEN_TOLERANCIA
	,0 --ES_CRITICA_GATING
	,0.5 --PESO_REGLA
	,CURRENT_USER --RESPONSABLE
	,'activo' -- ESTADO
	,'2025-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_REGLA_ATRIBUTO VALUES (
	--NULL --REGLA_ID
	1 --DOMINIO_ID
	,3 --ATRIBUTO_ID
	,1 --DIMENSION_CALIDAD_ID
	,'El teléfono de la entidad debe tener un formato válido' --DESCRIPCION_REGLA
	,'^(\+)?(\(?\d+\)?)(([\s-]+)?(\d+)){0,}$' --EXPRESION_REGULAR
	,0.8 --UMBRAL_MINIMO
	,0.05 --MARGEN_TOLERANCIA
	,0 --ES_CRITICA_GATING
	,1 --PESO_REGLA
	,CURRENT_USER --RESPONSABLE
	,'activo' -- ESTADO
	,'2025-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_REGLA_ATRIBUTO VALUES (
	--NULL --REGLA_ID
	1 --DOMINIO_ID
	,4 --ATRIBUTO_ID
	,1 --DIMENSION_CALIDAD_ID
	,'La página web de la entidad debe tener un formato válido' --DESCRIPCION_REGLA
	,'^(http|HTTP|https|HTTPS)?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&\/=]*)$' --EXPRESION_REGULAR
	,0.8 --UMBRAL_MINIMO
	,0.05 --MARGEN_TOLERANCIA
	,0 --ES_CRITICA_GATING
	,1 --PESO_REGLA
	,CURRENT_USER --RESPONSABLE
	,'activo' -- ESTADO
	,'2025-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_REGLA_ATRIBUTO VALUES (
	--NULL --REGLA_ID
	1 --DOMINIO_ID
	,5 --ATRIBUTO_ID
	,1 --DIMENSION_CALIDAD_ID
	,'La latitud de la entidad debe tener un formato válido' --DESCRIPCION_REGLA
	,'^(-?[1-8]?\d(?:\.\d{1,18})?|90(?:\.0{1,18})?)$' --EXPRESION_REGULAR
	,0.8 --UMBRAL_MINIMO
	,0.05 --MARGEN_TOLERANCIA
	,0 --ES_CRITICA_GATING
	,1 --PESO_REGLA
	,CURRENT_USER --RESPONSABLE
	,'activo' -- ESTADO
	,'2025-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

INSERT INTO CALIDAD.DQ_REGLA_ATRIBUTO VALUES (
	--NULL --REGLA_ID
	1 --DOMINIO_ID
	,6 --ATRIBUTO_ID
	,1 --DIMENSION_CALIDAD_ID
	,'La longitud de la entidad debe tener un formato válido' --DESCRIPCION_REGLA
	,'^(-?(?:1[0-7]|[1-9])?\d(?:\.\d{1,18})?|180(?:\.0{1,18})?)$' --EXPRESION_REGULAR
	,0.8 --UMBRAL_MINIMO
	,0.05 --MARGEN_TOLERANCIA
	,0 --ES_CRITICA_GATING
	,1 --PESO_REGLA
	,CURRENT_USER --RESPONSABLE
	,'activo' -- ESTADO
	,'2025-01-01' --VIGENCIA_INICIO
	,'2099-12-31' --VIGENCIA_FIN
	,'1' --VERSION
	,NULL --OBSERVACIONES
	,'2026-01-15T12:52:00.000' --FECHA_REGISTRO
	,NULL --FECHA_ACTUALIZACION
	,CURRENT_USER --USUARIO_REGISTRO
	,NULL --USUARIO_ACTUALIZACION
);

SELECT * FROM CALIDAD.DQ_REGLA_ATRIBUTO;
/**************************************************/


/**************************************************/
CREATE PROCEDURE CALIDAD.GESTION_EJECUCION
--ALTER PROCEDURE CALIDAD.GESTION_EJECUCION
(
    @EJECUCION_ID_ENTRADA INT = NULL,
	@ESTADO_EJECUCION VARCHAR(15) = NULL,
	@OBSERVACIONES VARCHAR(4000) = NULL,
    @EJECUCION_ID_SALIDA INT OUTPUT
)
AS
/*
-- =============================================
-- Author:      Mary Luz Perdomo Cruz
-- Create Date: 2025-11-28
-- Description: Realizar la creación / actualización del registro de ejecución
-- =============================================
*/
BEGIN
    SET NOCOUNT ON
	-- Variable para almacenar la consulta dimánica que realiza el perfilamiento
	DECLARE @CONSULTA_SQL NVARCHAR(4000)
	DECLARE @CONTEO_EJECUCION_ID INT
	-- Validar si el registro de ejecución existe
	IF @EJECUCION_ID_ENTRADA IS NOT NULL
	BEGIN
		SELECT @CONTEO_EJECUCION_ID = COUNT(EJECUCION_ID) FROM CALIDAD.DQ_EJECUCION WHERE EJECUCION_ID = @EJECUCION_ID_ENTRADA
	END
	
	IF @CONTEO_EJECUCION_ID = 0 OR @EJECUCION_ID_ENTRADA IS NULL
	BEGIN
		INSERT INTO CALIDAD.DQ_EJECUCION VALUES (
			--NULL --EJECUCION_ID
			'BATCH' --TIPO_FLUJO
			,CURRENT_TIMESTAMP --FECHA_INICIO
			,NULL --FECHA_FIN
			,NULL --VENTANA_INICIO
			,NULL --VENTANA_FIN
			,'iniciado' --ESTADO
			,'programado' --ORIGEN_DISPARO
			,'1' --VERSION_CONFIGURACION
			,NULL --OBSERVACIONES
			,CURRENT_TIMESTAMP --FECHA_REGISTRO
			,CURRENT_USER --USUARIO_REGISTRO
		)
		SET @EJECUCION_ID_SALIDA = SCOPE_IDENTITY()
	END
	ELSE
	BEGIN
		UPDATE CALIDAD.DQ_EJECUCION 
		SET 
			FECHA_FIN = CURRENT_TIMESTAMP
			,ESTADO = @ESTADO_EJECUCION
			,OBSERVACIONES = @OBSERVACIONES
		WHERE EJECUCION_ID = @EJECUCION_ID_ENTRADA
		SET @EJECUCION_ID_SALIDA = @EJECUCION_ID_ENTRADA
	END
END;
GO;

--DECLARE @EJECUCION_ID INT;
--EXEC CALIDAD.GESTION_EJECUCION @EJECUCION_ID_ENTRADA = NULL, @EJECUCION_ID_SALIDA = @EJECUCION_ID OUTPUT;
--SELECT * FROM [CALIDAD].[DQ_EJECUCION] WHERE EJECUCION_ID = @EJECUCION_ID;
--GO


CREATE PROCEDURE CALIDAD.EJECUCION
--ALTER PROCEDURE CALIDAD.EJECUCION
(
    @EJECUCION_ID INT OUTPUT
)
AS
/*
-- =============================================
-- Author:      Mary Luz Perdomo Cruz
-- Create Date: 2025-11-28
-- Description: Ejecutar el proceso de calidad
-- =============================================
*/
BEGIN
    SET NOCOUNT ON
	-- Variable para almacenar la consulta dimánica que realiza el perfilamiento
	DECLARE @CONSULTA_SQL NVARCHAR(4000)
	DECLARE @ID_EJECUCION_LOCAL INT
	
	BEGIN TRY
		
		-- Crear un nuevo registro de ejecución
		EXEC CALIDAD.GESTION_EJECUCION @EJECUCION_ID_ENTRADA = @EJECUCION_ID, @EJECUCION_ID_SALIDA = @ID_EJECUCION_LOCAL OUTPUT
		
		-- Calcular el resultado de calidad a nivel de regla-detalle
		DECLARE CUR_CONSULTAS CURSOR LOCAL FOR
			--Generador de consultas dinámicas
			SELECT
				'--dinamyc sql
				WITH VALIDACION AS (
						SELECT 
							'+STR(@ID_EJECUCION_LOCAL)+' AS EJECUCION_ID
							,A.DOMINIO_ID AS DOMINIO_ID
							,A.ATRIBUTO_ID AS ATRIBUTO_ID
							,R.REGLA_ID AS REGLA_ID
							,R.DIMENSION_CALIDAD_ID AS DIMENSION_CALIDAD_ID
							,SRC.DM_INSTITUCION_COD_INSTITUCION AS ID_REGISTRO_FUENTE
							,REGEXP_COUNT( TRIM( COALESCE( SRC.'+C.COLUMN_NAME+', '''' ) ), R.EXPRESION_REGULAR ) AS RESULTADO_VALIDACION
							,TRIM( COALESCE( SRC.'+C.COLUMN_NAME+', '''' ) ) AS VALOR_OBSERVADO
						FROM CALIDAD.DQ_REGLA_ATRIBUTO AS R
						LEFT JOIN CALIDAD.DQ_ATRIBUTO AS A 
							ON R.ATRIBUTO_ID = A.ATRIBUTO_ID 
						CROSS JOIN FUENTE.ENTIDAD_PUBLICA_COLOMBIA AS SRC
						WHERE 1 = 1
							AND A.NOMBRE_TECNICO = '''+C.COLUMN_NAME+'''
				)
				INSERT INTO CALIDAD.DQ_RESULTADO_REGLA_DETALLE
				SELECT
					EJECUCION_ID
					,DOMINIO_ID
					,ATRIBUTO_ID
					,REGLA_ID
					,DIMENSION_CALIDAD_ID
					,ID_REGISTRO_FUENTE
					,VALOR_OBSERVADO
					/*,CASE 
						WHEN RESULTADO_VALIDACION IS NULL THEN -1 
						WHEN RESULTADO_VALIDACION >= 1 THEN 0 
						WHEN RESULTADO_VALIDACION = 0 THEN 1 
						ELSE -2 
					END AS RESULTADO*/
					,CASE 
						WHEN RESULTADO_VALIDACION IS NULL THEN ''No aplica''
						WHEN RESULTADO_VALIDACION >= 1 THEN ''CUMPLE'' 
						WHEN RESULTADO_VALIDACION = 0 THEN ''NO CUMPLE''
						ELSE ''<<OTRO>>'' 
					END
					,NULL
					,NULL
					,CURRENT_TIMESTAMP
				FROM VALIDACION;
				' AS SQL_TXT
			FROM information_schema.tables AS T
			JOIN information_schema.COLUMNS AS C
			ON T.TABLE_CATALOG = C.TABLE_CATALOG
				AND T.TABLE_SCHEMA = C.TABLE_SCHEMA
				AND T.TABLE_NAME = C.TABLE_NAME
			WHERE 1 = 1
				AND T.TABLE_SCHEMA = 'FUENTE'
				AND T.TABLE_NAME = 'ENTIDAD_PUBLICA_COLOMBIA'

		-- Limpiar ejecuciones previas con la misma fecha
		DELETE FROM CALIDAD.DQ_RESULTADO_REGLA_DETALLE WHERE EJECUCION_ID = @ID_EJECUCION_LOCAL

		-- Abrir el cursor
		OPEN CUR_CONSULTAS
		-- Traer el primer registro
		FETCH NEXT FROM CUR_CONSULTAS INTO @CONSULTA_SQL
		-- Recorrer el cursor mientras sea posible
		WHILE @@FETCH_STATUS = 0
		BEGIN
			-- Ejecutar la consulta dinámica
			--PRINT 'consulta: ' + @CONSULTA_SQL;
			EXEC sp_executesql @CONSULTA_SQL
			-- Traer el siguiente registro
			FETCH NEXT FROM CUR_CONSULTAS INTO @CONSULTA_SQL
		END
		-- Cerrar el cursos
		CLOSE CUR_CONSULTAS
		-- Eliminar el cursor
		DEALLOCATE CUR_CONSULTAS

		
		-- Calcular el resultado de calidad a nivel de regla
		-- Limpiar ejecuciones previas con la misma fecha
		DELETE FROM CALIDAD.DQ_RESULTADO_REGLA WHERE EJECUCION_ID = @ID_EJECUCION_LOCAL
		
		SET @CONSULTA_SQL = '
		WITH RESULTADO_X_REGLA AS (
			SELECT
				RD.EJECUCION_ID
				,RD.DOMINIO_ID
				,RD.ATRIBUTO_ID
				,RD.REGLA_ID
				,RD.DIMENSION_CALIDAD_ID
				,COUNT(1) AS REGISTROS_EVALUADOS
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''CUMPLE'' THEN 1 ELSE 0 END ) AS REGISTROS_CUMPLE
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''PARCIAL'' THEN 1 ELSE 0 END ) AS REGISTROS_CUMPLE_PARCIAL
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''NO CUMPLE'' THEN 1 ELSE 0 END ) AS REGISTROS_NO_CUMPLE
				,R.UMBRAL_MINIMO
				,R.MARGEN_TOLERANCIA
				,R.PESO_REGLA
			FROM CALIDAD.DQ_RESULTADO_REGLA_DETALLE AS RD
			LEFT JOIN CALIDAD.DQ_REGLA_ATRIBUTO AS R
				ON RD.REGLA_ID = R.REGLA_ID
			WHERE EJECUCION_ID = '+STR(@ID_EJECUCION_LOCAL)+'
			GROUP BY RD.EJECUCION_ID
				,RD.DOMINIO_ID
				,RD.ATRIBUTO_ID
				,RD.REGLA_ID
				,RD.DIMENSION_CALIDAD_ID
				,R.UMBRAL_MINIMO
				,R.MARGEN_TOLERANCIA
				,R.PESO_REGLA
		)
		INSERT INTO CALIDAD.DQ_RESULTADO_REGLA
		SELECT
			--NULL --RESULTADO_REGLA_ID
			RXR.EJECUCION_ID --EJECUCION_ID
			,RXR.DOMINIO_ID --DOMINIO_ID
			,RXR.ATRIBUTO_ID --ATRIBUTO_ID 
			,RXR.REGLA_ID --REGLA_ID
			,RXR.DIMENSION_CALIDAD_ID --DIMENSION_CALIDAD_ID
			,RXR.REGISTROS_EVALUADOS
			,RXR.REGISTROS_CUMPLE
			,RXR.REGISTROS_CUMPLE_PARCIAL
			,RXR.REGISTROS_NO_CUMPLE
			,RXR.REGISTROS_CUMPLE / ( RXR.REGISTROS_EVALUADOS * 1. ) --TASA_CUMPLIMIENTO
			,RXR.REGISTROS_NO_CUMPLE / ( RXR.REGISTROS_EVALUADOS * 1. ) --TASA_ERROR
			,RXR.UMBRAL_MINIMO --UMBRAL_MINIMO
			,RXR.MARGEN_TOLERANCIA --MARGEN_TOLERANCIA
			,CASE 
				WHEN RXR.REGISTROS_CUMPLE / ( RXR.REGISTROS_EVALUADOS * 1. ) < RXR.UMBRAL_MINIMO - RXR.MARGEN_TOLERANCIA THEN 0 
				ELSE 1 
			END --MCA_UMBRAL_CUMPLIDO
			,RXR.PESO_REGLA
			,( RXR.REGISTROS_CUMPLE / ( RXR.REGISTROS_EVALUADOS * 1. ) ) * RXR.PESO_REGLA --SCORE_REGLA
			,CURRENT_TIMESTAMP --FECHA_CALCULO
		FROM RESULTADO_X_REGLA AS RXR
		'
		EXEC sp_executesql @CONSULTA_SQL
		
		-- Calcular el resultado de calidad a nivel de atributo
		-- Limpiar ejecuciones previas con la misma fecha
		DELETE FROM CALIDAD.DQ_RESULTADO_ATRIBUTO WHERE EJECUCION_ID = @ID_EJECUCION_LOCAL
		
		SET @CONSULTA_SQL = '
		WITH RESULTADO_X_ATRIBUTO AS (
			SELECT
				RD.EJECUCION_ID
				,RD.DOMINIO_ID
				,RD.ATRIBUTO_ID
				,RD.DIMENSION_CALIDAD_ID
				,COUNT(1) AS REGISTROS_EVALUADOS
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''CUMPLE'' THEN 1 ELSE 0 END ) AS REGISTROS_VALIDOS
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''NO CUMPLE'' THEN 1 ELSE 0 END ) AS REGISTROS_INVALIDOS
				,A.PESO_ATRIBUTO
			FROM CALIDAD.DQ_RESULTADO_REGLA_DETALLE AS RD
			LEFT JOIN CALIDAD.DQ_ATRIBUTO AS A
				ON RD.ATRIBUTO_ID = A.ATRIBUTO_ID
			WHERE EJECUCION_ID = '+STR(@ID_EJECUCION_LOCAL)+'
			GROUP BY RD.EJECUCION_ID
				,RD.DOMINIO_ID
				,RD.ATRIBUTO_ID
				,RD.DIMENSION_CALIDAD_ID
				,A.PESO_ATRIBUTO
		)
		INSERT INTO CALIDAD.DQ_RESULTADO_ATRIBUTO
		SELECT
			--NULL --RESULTADO_ATRIBUTO_ID
			RXA.EJECUCION_ID --EJECUCION_ID
			,RXA.DOMINIO_ID --DOMINIO_ID
			,RXA.ATRIBUTO_ID --ATRIBUTO_ID 
			,RXA.DIMENSION_CALIDAD_ID --DIMENSION_CALIDAD_ID
			,''1'' --VERSION_ATRIBUTO
			,RXA.REGISTROS_EVALUADOS --REGISTROS_EVALUADOS
			,RXA.REGISTROS_VALIDOS --REGISTROS_VALIDOS
			,RXA.REGISTROS_INVALIDOS --REGISTROS_INVALIDOS
			,RXA.REGISTROS_VALIDOS / ( RXA.REGISTROS_EVALUADOS * 1. ) --SCORE_DIMENSION_ATRIBUTO
			,RXA.PESO_ATRIBUTO --PESO_ATRIBUTO
			,( RXA.REGISTROS_VALIDOS / ( RXA.REGISTROS_EVALUADOS * 1. ) ) * RXA.PESO_ATRIBUTO --SCORE_ATRIBUTO_PONDERADO
			,CURRENT_TIMESTAMP --FECHA_CALCULO
		FROM RESULTADO_X_ATRIBUTO AS RXA
		'
		EXEC sp_executesql @CONSULTA_SQL
		
		-- Calcular el resultado de calidad a nivel de dominio
		-- Limpiar ejecuciones previas con la misma fecha
		DELETE FROM CALIDAD.DQ_RESULTADO_DOMINIO WHERE EJECUCION_ID = @ID_EJECUCION_LOCAL
		
		SET @CONSULTA_SQL = '
		WITH RESULTADO_X_DOMINIO_DIM AS (
			SELECT
				RD.EJECUCION_ID
				,RD.DOMINIO_ID
				,RD.DIMENSION_CALIDAD_ID
				,COUNT(1) AS REGISTROS_EVALUADOS
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''CUMPLE'' THEN 1 ELSE 0 END ) AS REGISTROS_VALIDOS
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''NO CUMPLE'' THEN 1 ELSE 0 END ) AS REGISTROS_INVALIDOS
			FROM CALIDAD.DQ_RESULTADO_REGLA_DETALLE AS RD
			WHERE EJECUCION_ID = '+STR(@ID_EJECUCION_LOCAL)+'
			GROUP BY RD.EJECUCION_ID
				,RD.DOMINIO_ID
				,RD.DIMENSION_CALIDAD_ID
		), RESULTADO_X_DOMINIO AS (
		SELECT
				RD.EJECUCION_ID
				,RD.DOMINIO_ID
				,COUNT(1) AS REGISTROS_EVALUADOS
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''CUMPLE'' THEN 1 ELSE 0 END ) AS REGISTROS_VALIDOS
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''NO CUMPLE'' THEN 1 ELSE 0 END ) AS REGISTROS_INVALIDOS
			FROM CALIDAD.DQ_RESULTADO_REGLA_DETALLE AS RD
			WHERE EJECUCION_ID = '+STR(@ID_EJECUCION_LOCAL)+'
			GROUP BY RD.EJECUCION_ID
				,RD.DOMINIO_ID
		)
		INSERT INTO CALIDAD.DQ_RESULTADO_DOMINIO
		SELECT
			--NULL --RESULTADO_DOMINIO_ID
			RXDD.EJECUCION_ID --EJECUCION_ID
			,RXDD.DOMINIO_ID --DOMINIO_ID
			,RXDD.DIMENSION_CALIDAD_ID --DIMENSION_CALIDAD_ID
			,''1'' --VERSION_DOMINIO
			,RXDD.REGISTROS_EVALUADOS --REGISTROS_EVALUADOS
			,RXDD.REGISTROS_VALIDOS --REGISTROS_VALIDOS
			,RXDD.REGISTROS_INVALIDOS --REGISTROS_INVALIDOS
			,RXDD.REGISTROS_VALIDOS / ( RXDD.REGISTROS_EVALUADOS * 1. ) --SCORE_DIMENSION_DOMINIO
			,RXD.REGISTROS_VALIDOS / ( RXD.REGISTROS_EVALUADOS * 1. ) --SCORE_DOMINIO_TOTAL
			,CURRENT_TIMESTAMP --FECHA_CALCULO
		FROM RESULTADO_X_DOMINIO_DIM AS RXDD
		LEFT JOIN RESULTADO_X_DOMINIO AS RXD
		ON RXDD.EJECUCION_ID = RXD.EJECUCION_ID
		AND RXDD.DOMINIO_ID = RXD.DOMINIO_ID

		'
		EXEC sp_executesql @CONSULTA_SQL
		
		-- Calcular el resultado de la ejecución a nivel de dominio
		-- Limpiar ejecuciones previas con la misma fecha
		DELETE FROM CALIDAD.DQ_EJECUCION_DOMINIO WHERE EJECUCION_ID = @ID_EJECUCION_LOCAL
		
		SET @CONSULTA_SQL = '
		WITH RESULTADO_X_DOMINIO AS (
			SELECT
				RD.EJECUCION_ID
				,RD.DOMINIO_ID
				,COUNT(1) AS REGISTROS_EVALUADOS
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''CUMPLE'' THEN 1 ELSE 0 END ) AS REGISTROS_VALIDOS
				,SUM( CASE WHEN RD.ESTADO_VALIDACION = ''NO CUMPLE'' THEN 1 ELSE 0 END ) AS REGISTROS_INVALIDOS
			FROM CALIDAD.DQ_RESULTADO_REGLA_DETALLE AS RD
			WHERE EJECUCION_ID = '+STR(@ID_EJECUCION_LOCAL)+'
			GROUP BY RD.EJECUCION_ID
				,RD.DOMINIO_ID
		)
		INSERT INTO CALIDAD.DQ_EJECUCION_DOMINIO
		SELECT
			RXD.EJECUCION_ID --EJECUCION_ID
			,RXD.DOMINIO_ID --DOMINIO_ID
			,''1'' --VERSION_DOMINIO
			,RXD.REGISTROS_EVALUADOS --REGISTROS_EVALUADOS
			,RXD.REGISTROS_VALIDOS --REGISTROS_VALIDOS
			,RXD.REGISTROS_INVALIDOS --REGISTROS_INVALIDOS
			,RXD.REGISTROS_VALIDOS / ( RXD.REGISTROS_EVALUADOS * 1. ) --SCORE_DOMINIO
			,''finalizado'' --ESTADO
		FROM RESULTADO_X_DOMINIO AS RXD
		'
		EXEC sp_executesql @CONSULTA_SQL
		
		-- Actualizar el registro de ejecución
		EXEC CALIDAD.GESTION_EJECUCION @EJECUCION_ID_ENTRADA = @ID_EJECUCION_LOCAL, @ESTADO_EJECUCION = 'finalizado', @EJECUCION_ID_SALIDA = @ID_EJECUCION_LOCAL OUTPUT
	END TRY
	BEGIN CATCH
		DECLARE @MENSAJE_ERROR VARCHAR(4000)
		SET @MENSAJE_ERROR = 'Error'+STR(ERROR_NUMBER())+': '+ERROR_MESSAGE()
		EXEC CALIDAD.GESTION_EJECUCION @EJECUCION_ID_ENTRADA = @ID_EJECUCION_LOCAL, @ESTADO_EJECUCION = 'error', @OBSERVACIONES = @MENSAJE_ERROR, @EJECUCION_ID_SALIDA = @ID_EJECUCION_LOCAL OUTPUT
	END CATCH;
	
	SET @EJECUCION_ID = @ID_EJECUCION_LOCAL
END;
GO;

DECLARE @EJECUCION_ID INT;
SET @EJECUCION_ID = NULL;
EXEC CALIDAD.EJECUCION @EJECUCION_ID = @EJECUCION_ID OUTPUT;
SELECT COUNT(1) FROM CALIDAD.DQ_RESULTADO_REGLA_DETALLE WHERE EJECUCION_ID = @EJECUCION_ID;
SELECT COUNT(1) FROM CALIDAD.DQ_RESULTADO_REGLA WHERE EJECUCION_ID = @EJECUCION_ID;
SELECT COUNT(1) FROM CALIDAD.DQ_RESULTADO_ATRIBUTO WHERE EJECUCION_ID = @EJECUCION_ID;
SELECT COUNT(1) FROM CALIDAD.DQ_RESULTADO_DOMINIO WHERE EJECUCION_ID = @EJECUCION_ID;
SELECT COUNT(1) FROM CALIDAD.DQ_EJECUCION_DOMINIO WHERE EJECUCION_ID = @EJECUCION_ID;
SELECT * FROM CALIDAD.DQ_EJECUCION WHERE EJECUCION_ID = @EJECUCION_ID;
/**************************************************/


